# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VreservedSignalTable extends _ModuleTable

signal inserted(row: VreservedThing)
signal updated(old_row: VreservedThing, new_row: VreservedThing)
signal deleted(row: VreservedThing)

var func_: VreservedSignalFuncUniqueIndex
var class_: VreservedSignalClassBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"signal"
	func_ = VreservedSignalFuncUniqueIndex.new(p_local_db)
	class_ = VreservedSignalClassBTreeIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VreservedThing]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VreservedThing] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VreservedThing]:
	var rows: Array = super(predicate)
	var typed_array: Array[VreservedThing] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VreservedThing:
	return super(predicate) as VreservedThing

func find_by(field: StringName, value: Variant) -> Array[VreservedThing]:
	var rows: Array = super(field, value)
	var typed_array: Array[VreservedThing] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VreservedThing:
	return super(field, value) as VreservedThing

func find_by_func_(value: int) -> Array[VreservedThing]:
	var row: VreservedThing = func_.find(value)
	var result: Array[VreservedThing] = []
	if row != null:
		result.append(row)
	return result

func first_by_func_(value: int) -> VreservedThing:
	return func_.find(value)

func find_by_signal_(value: int) -> Array[VreservedThing]:
	return find_by(&"signal_", value)

func first_by_signal_(value: int) -> VreservedThing:
	return first_by(&"signal_", value)

func find_by_class_(value: int) -> Array[VreservedThing]:
	return class_.filter(value)

func first_by_class_(value: int) -> VreservedThing:
	return class_._first_row(value) as VreservedThing

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VreservedThing)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VreservedThing, new_row as VreservedThing)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VreservedThing)
