# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VreservedAlphaFuncUniqueIndex extends _ModuleTableUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	_table_name = &"alpha"
	_field_name = &"func_"
	_read_primary_key_rows(p_local_db)

func find(col_val: int) -> VreservedThing:
	return _find_by_primary_key(col_val)
