# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VreservedSignalFuncUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, VreservedThing] = {}

func _init(p_local_db: LocalDatabase) -> void:
	_table_name = &"signal"
	_field_name = &"func_"
	_connect_cache_to_db(_cache, p_local_db)

func find(col_val: int) -> VreservedThing:
	return _cache.get(col_val, null)
