# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VtypesOneU256 extends _ModuleTableType

const module_name : String = "Vtypes"
const table_names: Array[StringName] = [&'one_u_256']
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"n": &"u256" }

@export var n: PackedByteArray

## 0. n: PackedByteArray[br]
static func create(p_n: PackedByteArray) -> VtypesOneU256:
	var result: VtypesOneU256 = VtypesOneU256.new()
	result.n = p_n
	return result
