# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VtypesOneUuid extends _ModuleTableType

const module_name : String = "Vtypes"
const table_names: Array[StringName] = [&'one_uuid']
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"u": &"u128" }

@export var u: PackedByteArray

## 0. u: PackedByteArray[br]
static func create(p_u: PackedByteArray) -> VtypesOneUuid:
	var result: VtypesOneUuid = VtypesOneUuid.new()
	result.u = p_u
	return result
