# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name Vtypes2Thing extends _ModuleTableType

const module_name : String = "Vtypes2"
const table_names: Array[StringName] = [&'thing']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"label": &"string" }

@export var id: int
@export var label: String

## 0. id: int[br]
## 1. label: String[br]
static func create(p_id: int, p_label: String) -> Vtypes2Thing:
	var result: Vtypes2Thing = Vtypes2Thing.new()
	result.id = p_id
	result.label = p_label
	return result


## Whether two Vtypes2Thing values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: Vtypes2Thing, p_rhs: Vtypes2Thing) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.id != p_rhs.id:
		return false
	if p_lhs.label != p_rhs.label:
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: Vtypes2Thing = p_other as Vtypes2Thing
	if p_rhs == null:
		return false
	if self.id != p_rhs.id:
		return false
	if self.label != p_rhs.label:
		return false
	return true
