# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name Vtypes2DurRow extends _ModuleTableType

const module_name : String = "Vtypes2"
const table_names: Array[StringName] = [&'dur_row']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"d": &"i64" }

@export var id: int
@export var d: int

## 0. id: int[br]
## 1. d: int[br]
static func create(p_id: int, p_d: int) -> Vtypes2DurRow:
	var result: Vtypes2DurRow = Vtypes2DurRow.new()
	result.id = p_id
	result.d = p_d
	return result
