# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name Vtypes2SeqRow extends _ModuleTableType

const module_name : String = "Vtypes2"
const table_names: Array[StringName] = [&'seq_row']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"v": &"u32" }

@export var id: int
@export var v: int

## 0. id: int[br]
## 1. v: int[br]
static func create(p_id: int, p_v: int) -> Vtypes2SeqRow:
	var result: Vtypes2SeqRow = Vtypes2SeqRow.new()
	result.id = p_id
	result.v = p_v
	return result


## Whether two Vtypes2SeqRow values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: Vtypes2SeqRow, p_rhs: Vtypes2SeqRow) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.id != p_rhs.id:
		return false
	if p_lhs.v != p_rhs.v:
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: Vtypes2SeqRow = p_other as Vtypes2SeqRow
	if p_rhs == null:
		return false
	if self.id != p_rhs.id:
		return false
	if self.v != p_rhs.v:
		return false
	return true
