# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name Vtypes2Thing extends _ModuleTableType

const module_name : String = "Vtypes2"
const table_names: Array[StringName] = [&'thing']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"label": &"string" }

@export var id: int
@export var label: String

## 0. id: int[br]
## 1. label: String[br]
static func create(p_id: int, p_label: String) -> Vtypes2Thing:
	var result: Vtypes2Thing = Vtypes2Thing.new()
	result.id = p_id
	result.label = p_label
	return result
