# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VsubmodLibLibDataTable extends _ModuleTable

signal inserted(row: VsubmodLibLibData)
signal updated(old_row: VsubmodLibLibData, new_row: VsubmodLibLibData)
signal deleted(row: VsubmodLibLibData)

var id: VsubmodLibLibDataIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"lib.lib_data"
	id = VsubmodLibLibDataIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VsubmodLibLibData]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VsubmodLibLibData] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VsubmodLibLibData]:
	var rows: Array = super(predicate)
	var typed_array: Array[VsubmodLibLibData] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VsubmodLibLibData:
	return super(predicate) as VsubmodLibLibData

func find_by(field: StringName, value: Variant) -> Array[VsubmodLibLibData]:
	var rows: Array = super(field, value)
	var typed_array: Array[VsubmodLibLibData] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VsubmodLibLibData:
	return super(field, value) as VsubmodLibLibData

func find_by_id(value: int) -> Array[VsubmodLibLibData]:
	var row: VsubmodLibLibData = id.find(value)
	var result: Array[VsubmodLibLibData] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VsubmodLibLibData:
	return id.find(value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VsubmodLibLibData)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VsubmodLibLibData, new_row as VsubmodLibLibData)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VsubmodLibLibData)
