# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VsubmodRootThingTable extends _ModuleTable

signal inserted(row: VsubmodRootThing)
signal updated(old_row: VsubmodRootThing, new_row: VsubmodRootThing)
signal deleted(row: VsubmodRootThing)

var id: VsubmodRootThingIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"root_thing"
	id = VsubmodRootThingIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VsubmodRootThing]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VsubmodRootThing] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VsubmodRootThing]:
	var rows: Array = super(predicate)
	var typed_array: Array[VsubmodRootThing] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VsubmodRootThing:
	return super(predicate) as VsubmodRootThing

func find_by(field: StringName, value: Variant) -> Array[VsubmodRootThing]:
	var rows: Array = super(field, value)
	var typed_array: Array[VsubmodRootThing] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VsubmodRootThing:
	return super(field, value) as VsubmodRootThing

func find_by_id(value: int) -> Array[VsubmodRootThing]:
	var row: VsubmodRootThing = id.find(value)
	var result: Array[VsubmodRootThing] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VsubmodRootThing:
	return id.find(value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VsubmodRootThing)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VsubmodRootThing, new_row as VsubmodRootThing)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VsubmodRootThing)
