# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VsubmodLibLibSecretTable extends _ModuleTable

signal inserted(row: VsubmodLibLibSecret)
signal updated(old_row: VsubmodLibLibSecret, new_row: VsubmodLibLibSecret)
signal deleted(row: VsubmodLibLibSecret)

var id: VsubmodLibLibSecretIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"lib.lib_secret"
	id = VsubmodLibLibSecretIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VsubmodLibLibSecret]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VsubmodLibLibSecret] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VsubmodLibLibSecret]:
	var rows: Array = super(predicate)
	var typed_array: Array[VsubmodLibLibSecret] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VsubmodLibLibSecret:
	return super(predicate) as VsubmodLibLibSecret

func find_by(field: StringName, value: Variant) -> Array[VsubmodLibLibSecret]:
	var rows: Array = super(field, value)
	var typed_array: Array[VsubmodLibLibSecret] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VsubmodLibLibSecret:
	return super(field, value) as VsubmodLibLibSecret

func find_by_id(value: int) -> Array[VsubmodLibLibSecret]:
	var row: VsubmodLibLibSecret = id.find(value)
	var result: Array[VsubmodLibLibSecret] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VsubmodLibLibSecret:
	return id.find(value)

func find_by_secret(value: String) -> Array[VsubmodLibLibSecret]:
	return find_by(&"secret", value)

func first_by_secret(value: String) -> VsubmodLibLibSecret:
	return first_by(&"secret", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VsubmodLibLibSecret)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VsubmodLibLibSecret, new_row as VsubmodLibLibSecret)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VsubmodLibLibSecret)
