# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VsubmodAuthAuthSessionTable extends _ModuleTable

signal inserted(row: VsubmodAuthAuthSession)
signal updated(old_row: VsubmodAuthAuthSession, new_row: VsubmodAuthAuthSession)
signal deleted(row: VsubmodAuthAuthSession)

var id: VsubmodAuthAuthSessionIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"auth.auth_session"
	id = VsubmodAuthAuthSessionIdUniqueIndex.new(p_local_db)
	_relay_row_signals()

func iter() -> Array[VsubmodAuthAuthSession]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VsubmodAuthAuthSession] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VsubmodAuthAuthSession]:
	var rows: Array = super(predicate)
	var typed_array: Array[VsubmodAuthAuthSession] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VsubmodAuthAuthSession:
	return super(predicate) as VsubmodAuthAuthSession

func find_by(field: StringName, value: Variant) -> Array[VsubmodAuthAuthSession]:
	var rows: Array = super(field, value)
	var typed_array: Array[VsubmodAuthAuthSession] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VsubmodAuthAuthSession:
	return super(field, value) as VsubmodAuthAuthSession

func find_by_id(value: int) -> Array[VsubmodAuthAuthSession]:
	var row: VsubmodAuthAuthSession = id.find(value)
	var result: Array[VsubmodAuthAuthSession] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VsubmodAuthAuthSession:
	return id.find(value)

func find_by_token(value: String) -> Array[VsubmodAuthAuthSession]:
	return find_by(&"token", value)

func first_by_token(value: String) -> VsubmodAuthAuthSession:
	return first_by(&"token", value)
