# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VsubmodAuthBazBazItemsTable extends _ModuleTable

signal inserted(row: VsubmodAuthBazBazItems)
signal updated(old_row: VsubmodAuthBazBazItems, new_row: VsubmodAuthBazBazItems)
signal deleted(row: VsubmodAuthBazBazItems)

var id: VsubmodAuthBazBazItemsIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"auth.baz.baz_items"
	id = VsubmodAuthBazBazItemsIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VsubmodAuthBazBazItems]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VsubmodAuthBazBazItems] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VsubmodAuthBazBazItems]:
	var rows: Array = super(predicate)
	var typed_array: Array[VsubmodAuthBazBazItems] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VsubmodAuthBazBazItems:
	return super(predicate) as VsubmodAuthBazBazItems

func find_by(field: StringName, value: Variant) -> Array[VsubmodAuthBazBazItems]:
	var rows: Array = super(field, value)
	var typed_array: Array[VsubmodAuthBazBazItems] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VsubmodAuthBazBazItems:
	return super(field, value) as VsubmodAuthBazBazItems

func find_by_id(value: int) -> Array[VsubmodAuthBazBazItems]:
	var row: VsubmodAuthBazBazItems = id.find(value)
	var result: Array[VsubmodAuthBazBazItems] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VsubmodAuthBazBazItems:
	return id.find(value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VsubmodAuthBazBazItems)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VsubmodAuthBazBazItems, new_row as VsubmodAuthBazBazItems)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VsubmodAuthBazBazItems)
