# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VeventThing extends _ModuleTableType

const module_name : String = "Vevent"
const table_names: Array[StringName] = [&'thing']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u32", &"score": &"u32" }

@export var id: int
@export var score: int

## 0. id: int[br]
## 1. score: int[br]
static func create(p_id: int, p_score: int) -> VeventThing:
	var result: VeventThing = VeventThing.new()
	result.id = p_id
	result.score = p_score
	return result
