# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VeventDamage extends _ModuleTableType

const module_name : String = "Vevent"
const table_names: Array[StringName] = [&'damage']
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u32", &"target": &"u32", &"amount": &"u32" }

@export var id: int
@export var target: int
@export var amount: int

## 0. id: int[br]
## 1. target: int[br]
## 2. amount: int[br]
static func create(p_id: int, p_target: int, p_amount: int) -> VeventDamage:
	var result: VeventDamage = VeventDamage.new()
	result.id = p_id
	result.target = p_target
	result.amount = p_amount
	return result
