# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name BlackholioModuleProcedures extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## Returns: BlackholioResultVector3String [br]
func probe_vector_3() -> SpacetimeDBProcedureCall:
	return _client.call_procedure('probe_vector_3', [], [], &'BlackholioResultVector3String')

