# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name BlackholioModuleClient extends SpacetimeDBClient

var reducers: BlackholioModuleReducers
var procedures: BlackholioModuleProcedures
var db: BlackholioModuleDb

func _init() -> void:
	module_name = "Blackholio"
	name = "BlackholioModule"
	reducers = preload('res://spacetime_bindings/schema/module_blackholio_reducers.gd').new(self)
	procedures = preload('res://spacetime_bindings/schema/module_blackholio_procedures.gd').new(self)

func _init_db(p_local_db: LocalDatabase) -> void:
	db = preload('res://spacetime_bindings/schema/module_blackholio_db.gd').new(p_local_db)
