# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name BlackholioTypes

const Circle = preload('res://spacetime_bindings/schema/types/blackholio_circle.gd')
const DbVector2 = preload('res://spacetime_bindings/schema/types/blackholio_db_vector_2.gd')
const Config = preload('res://spacetime_bindings/schema/types/blackholio_config.gd')
const Entity = preload('res://spacetime_bindings/schema/types/blackholio_entity.gd')
const Food = preload('res://spacetime_bindings/schema/types/blackholio_food.gd')
const Player = preload('res://spacetime_bindings/schema/types/blackholio_player.gd')
const ProbeRow = preload('res://spacetime_bindings/schema/types/blackholio_probe_row.gd')
const ProbeKind = preload('res://spacetime_bindings/schema/types/blackholio_probe_kind.gd')
const ResultVector3String = preload('res://spacetime_bindings/schema/types/blackholio_result_vector_3_string.gd')
