# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client

func change_color_random() -> SpacetimeDBReducerCall:
	return _client.call_reducer('change_color_random', [], [])

func clear_integration_tests() -> SpacetimeDBReducerCall:
	return _client.call_reducer('clear_integration_tests', [], [])

## 0. new_input: Vector2 [br]
## 1. global_position: Vector3 [br]
func move_user(new_input: Vector2, global_position: Vector3) -> SpacetimeDBReducerCall:
	return _client.call_reducer('move_user', [new_input, global_position], [&'vector2[f32,f32]', &'vector3[f32,f32,f32]'])

## 0. bytes: Array of int [br]
func save_my_bytes(bytes: Array[int]) -> SpacetimeDBReducerCall:
	return _client.call_reducer('save_my_bytes', [bytes], [&'u8'])

func start_integration_tests() -> SpacetimeDBReducerCall:
	return _client.call_reducer('start_integration_tests', [], [])

## 0. option: Option of String [br]
func test_option_single(option: Option) -> SpacetimeDBReducerCall:
	return _client.call_reducer('test_option_single', [option], [&'string'])

## 0. option: Option of Array of String [br]
func test_option_vec(option: Option) -> SpacetimeDBReducerCall:
	return _client.call_reducer('test_option_vec', [option], [&'vec_string'])

## 0. row: MainTestScheduledTable [br]
func test_scheduled_reducer(row: MainTestScheduledTable) -> SpacetimeDBReducerCall:
	return _client.call_reducer('test_scheduled_reducer', [row], [&'MainTestScheduledTable'])

## 0. message: MainMessage [br]
func test_struct(message: MainMessage) -> SpacetimeDBReducerCall:
	return _client.call_reducer('test_struct', [message], [&'MainMessage'])
