# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

const Lobby = preload('res://spacetime_bindings/schema/types/main_lobby.gd')
const TestTableDatatypes = preload('res://spacetime_bindings/schema/types/main_test_table_datatypes.gd')
enum TestEnum {
	A,
	B
}
const TestType = preload('res://spacetime_bindings/schema/types/main_test_type.gd')
const TestNestedEnum = preload('res://spacetime_bindings/schema/types/main_test_nested_enum.gd')
const TestScheduledTable = preload('res://spacetime_bindings/schema/types/main_test_scheduled_table.gd')
const Message = preload('res://spacetime_bindings/schema/types/main_message.gd')
const Damage = preload('res://spacetime_bindings/schema/types/main_damage.gd')
const User = preload('res://spacetime_bindings/schema/types/main_user.gd')
const UserData = preload('res://spacetime_bindings/schema/types/main_user_data.gd')
