# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name BlackholioCircleTable extends _ModuleTable

var entity_id: BlackholioCircleEntityIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"circle"
	entity_id = BlackholioCircleEntityIdUniqueIndex.new(p_local_db)

func iter() -> Array[BlackholioCircle]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[BlackholioCircle] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[BlackholioCircle]:
	var rows: Array = super(predicate)
	var typed_array: Array[BlackholioCircle] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> BlackholioCircle:
	return super(predicate) as BlackholioCircle

func find_by(field: StringName, value: Variant) -> Array[BlackholioCircle]:
	var rows: Array = super(field, value)
	var typed_array: Array[BlackholioCircle] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> BlackholioCircle:
	return super(field, value) as BlackholioCircle
