# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name BlackholioConsumeEntityEventTable extends _ModuleTable

signal inserted(row: BlackholioConsumeEntityEvent)
signal updated(old_row: BlackholioConsumeEntityEvent, new_row: BlackholioConsumeEntityEvent)
signal deleted(row: BlackholioConsumeEntityEvent)


func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"consume_entity_event"
	_relay_row_signals()

func iter() -> Array[BlackholioConsumeEntityEvent]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[BlackholioConsumeEntityEvent] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[BlackholioConsumeEntityEvent]:
	var rows: Array = super(predicate)
	var typed_array: Array[BlackholioConsumeEntityEvent] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> BlackholioConsumeEntityEvent:
	return super(predicate) as BlackholioConsumeEntityEvent

func find_by(field: StringName, value: Variant) -> Array[BlackholioConsumeEntityEvent]:
	var rows: Array = super(field, value)
	var typed_array: Array[BlackholioConsumeEntityEvent] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> BlackholioConsumeEntityEvent:
	return super(field, value) as BlackholioConsumeEntityEvent

func find_by_consumed_entity_id(value: int) -> Array[BlackholioConsumeEntityEvent]:
	return find_by(&"consumed_entity_id", value)

func first_by_consumed_entity_id(value: int) -> BlackholioConsumeEntityEvent:
	return first_by(&"consumed_entity_id", value)

func find_by_consumer_entity_id(value: int) -> Array[BlackholioConsumeEntityEvent]:
	return find_by(&"consumer_entity_id", value)

func first_by_consumer_entity_id(value: int) -> BlackholioConsumeEntityEvent:
	return first_by(&"consumer_entity_id", value)
