# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name BlackholioConfigTable extends _ModuleTable

var id: BlackholioConfigIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"config"
	id = BlackholioConfigIdUniqueIndex.new(p_local_db)

func iter() -> Array[BlackholioConfig]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[BlackholioConfig] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[BlackholioConfig]:
	var rows: Array = super(predicate)
	var typed_array: Array[BlackholioConfig] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> BlackholioConfig:
	return super(predicate) as BlackholioConfig

func find_by(field: StringName, value: Variant) -> Array[BlackholioConfig]:
	var rows: Array = super(field, value)
	var typed_array: Array[BlackholioConfig] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> BlackholioConfig:
	return super(field, value) as BlackholioConfig
