# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name BlackholioEntityTable extends _ModuleTable

var entity_id: BlackholioEntityEntityIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"entity"
	entity_id = BlackholioEntityEntityIdUniqueIndex.new(p_local_db)

func iter() -> Array[BlackholioEntity]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[BlackholioEntity] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[BlackholioEntity]:
	var rows: Array = super(predicate)
	var typed_array: Array[BlackholioEntity] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> BlackholioEntity:
	return super(predicate) as BlackholioEntity

func find_by(field: StringName, value: Variant) -> Array[BlackholioEntity]:
	var rows: Array = super(field, value)
	var typed_array: Array[BlackholioEntity] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> BlackholioEntity:
	return super(field, value) as BlackholioEntity
