# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name BlackholioCirclePlayerIdBTreeIndex extends _ModuleTableBTreeIndex

var _cache: Dictionary[int, Array] = {}

func _init(p_local_db: LocalDatabase) -> void:
	_table_name = &"circle"
	_field_name = &"player_id"
	_connect_cache_to_db(_cache, p_local_db)

func filter(col_val: int) -> Array[BlackholioCircle]:
	var typed_array: Array[BlackholioCircle] = []
	typed_array.assign(_cache.get(col_val, []))
	return typed_array
