# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name BlackholioCirclePlayerIdBTreeIndex extends _ModuleTableBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	_db = p_local_db
	_table_name = &"circle"
	_field_name = &"player_id"

func filter(col_val: int) -> Array[BlackholioCircle]:
	var rows: Array = _db.find_by(_table_name, _field_name, col_val)
	var typed_array: Array[BlackholioCircle] = []
	typed_array.assign(rows)
	return typed_array
