# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name BlackholioFoodTable extends _ModuleTable

var entity_id: BlackholioFoodEntityIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"food"
	entity_id = BlackholioFoodEntityIdUniqueIndex.new(p_local_db)

func iter() -> Array[BlackholioFood]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[BlackholioFood] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[BlackholioFood]:
	var rows: Array = super(predicate)
	var typed_array: Array[BlackholioFood] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> BlackholioFood:
	return super(predicate) as BlackholioFood

func find_by(field: StringName, value: Variant) -> Array[BlackholioFood]:
	var rows: Array = super(field, value)
	var typed_array: Array[BlackholioFood] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> BlackholioFood:
	return super(field, value) as BlackholioFood
