# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name BlackholioPlayerTable extends _ModuleTable

var player_id: BlackholioPlayerPlayerIdUniqueIndex
var identity: BlackholioPlayerIdentityUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"player"
	player_id = BlackholioPlayerPlayerIdUniqueIndex.new(p_local_db)
	identity = BlackholioPlayerIdentityUniqueIndex.new(p_local_db)

func iter() -> Array[BlackholioPlayer]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[BlackholioPlayer] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[BlackholioPlayer]:
	var rows: Array = super(predicate)
	var typed_array: Array[BlackholioPlayer] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> BlackholioPlayer:
	return super(predicate) as BlackholioPlayer

func find_by(field: StringName, value: Variant) -> Array[BlackholioPlayer]:
	var rows: Array = super(field, value)
	var typed_array: Array[BlackholioPlayer] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> BlackholioPlayer:
	return super(field, value) as BlackholioPlayer
