# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name BlackholioProbeRowTable extends _ModuleTable

signal inserted(row: BlackholioProbeRow)
signal updated(old_row: BlackholioProbeRow, new_row: BlackholioProbeRow)
signal deleted(row: BlackholioProbeRow)

var id: BlackholioProbeRowIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"probe_row"
	id = BlackholioProbeRowIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[BlackholioProbeRow]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[BlackholioProbeRow] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[BlackholioProbeRow]:
	var rows: Array = super(predicate)
	var typed_array: Array[BlackholioProbeRow] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> BlackholioProbeRow:
	return super(predicate) as BlackholioProbeRow

func find_by(field: StringName, value: Variant) -> Array[BlackholioProbeRow]:
	var rows: Array = super(field, value)
	var typed_array: Array[BlackholioProbeRow] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> BlackholioProbeRow:
	return super(field, value) as BlackholioProbeRow

func find_by_id(value: int) -> Array[BlackholioProbeRow]:
	var row: BlackholioProbeRow = id.find(value)
	var result: Array[BlackholioProbeRow] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> BlackholioProbeRow:
	return id.find(value)

func find_by_wide_unsigned(value: PackedByteArray) -> Array[BlackholioProbeRow]:
	return find_by(&"wide_unsigned", value)

func first_by_wide_unsigned(value: PackedByteArray) -> BlackholioProbeRow:
	return first_by(&"wide_unsigned", value)

func find_by_widest_unsigned(value: PackedByteArray) -> Array[BlackholioProbeRow]:
	return find_by(&"widest_unsigned", value)

func first_by_widest_unsigned(value: PackedByteArray) -> BlackholioProbeRow:
	return first_by(&"widest_unsigned", value)

func find_by_wide_signed(value: PackedByteArray) -> Array[BlackholioProbeRow]:
	return find_by(&"wide_signed", value)

func first_by_wide_signed(value: PackedByteArray) -> BlackholioProbeRow:
	return first_by(&"wide_signed", value)

func find_by_who(value: PackedByteArray) -> Array[BlackholioProbeRow]:
	return find_by(&"who", value)

func first_by_who(value: PackedByteArray) -> BlackholioProbeRow:
	return first_by(&"who", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as BlackholioProbeRow)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as BlackholioProbeRow, new_row as BlackholioProbeRow)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as BlackholioProbeRow)
