# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainTestNoPkTableTable extends _ModuleTable


func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	set_meta("table_name", "test_no_pk_table")

func iter() -> Array[MainViewType]:
	var rows: Array = super()
	var typed_array: Array[MainViewType] = []
	typed_array.assign(rows)
	return typed_array
