# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainTestTableDatatypesTU64UniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, MainTestTableDatatypes] = {}

func _init(p_local_db: LocalDatabase) -> void:
	set_meta("table_name", "test_table_datatypes")
	set_meta("field_name", "t_u_64")
	_connect_cache_to_db(_cache, p_local_db)

func find(col_val: int) -> MainTestTableDatatypes:
	return _cache.get(col_val, null)
