# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainUserDataHiddenTable extends _ModuleTable

var identity: MainUserDataHiddenIdentityUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	set_meta("table_name", "user_data_hidden")
	identity = MainUserDataHiddenIdentityUniqueIndex.new(p_local_db)

func iter() -> Array[MainUserData]:
	var rows: Array = super()
	var typed_array: Array[MainUserData] = []
	typed_array.assign(rows)
	return typed_array
