# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VtypesModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## 0. micros: int [br]
func add_schedule(micros: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('add_schedule', [micros], [&'i64'], &'')

## 0. n: PackedByteArray [br]
func insert_one_i_128(n: PackedByteArray) -> SpacetimeDBReducerCall:
	return _client.call_reducer('insert_one_i_128', [n], [&'i128'], &'')

## 0. n: PackedByteArray [br]
func insert_one_i_256(n: PackedByteArray) -> SpacetimeDBReducerCall:
	return _client.call_reducer('insert_one_i_256', [n], [&'i256'], &'')

## 0. n: PackedByteArray [br]
func insert_one_u_128(n: PackedByteArray) -> SpacetimeDBReducerCall:
	return _client.call_reducer('insert_one_u_128', [n], [&'u128'], &'')

## 0. n: PackedByteArray [br]
func insert_one_u_256(n: PackedByteArray) -> SpacetimeDBReducerCall:
	return _client.call_reducer('insert_one_u_256', [n], [&'u256'], &'')

## 0. u: PackedByteArray [br]
func insert_one_uuid(u: PackedByteArray) -> SpacetimeDBReducerCall:
	return _client.call_reducer('insert_one_uuid', [u], [&'u128'], &'')

## 0. _arg: VtypesMySchedule [br]
func on_schedule(_arg: VtypesMySchedule) -> SpacetimeDBReducerCall:
	return _client.call_reducer('on_schedule', [_arg], [&'VtypesMySchedule'], &'')

