# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VschedPlainTable extends _ModuleTable

signal inserted(row: VschedPlain)
signal updated(old_row: VschedPlain, new_row: VschedPlain)
signal deleted(row: VschedPlain)

var id: VschedPlainIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"plain"
	id = VschedPlainIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VschedPlain]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VschedPlain] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VschedPlain]:
	var rows: Array = super(predicate)
	var typed_array: Array[VschedPlain] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VschedPlain:
	return super(predicate) as VschedPlain

func find_by(field: StringName, value: Variant) -> Array[VschedPlain]:
	var rows: Array = super(field, value)
	var typed_array: Array[VschedPlain] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VschedPlain:
	return super(field, value) as VschedPlain

func find_by_id(value: int) -> Array[VschedPlain]:
	var row: VschedPlain = id.find(value)
	var result: Array[VschedPlain] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VschedPlain:
	return id.find(value)

func find_by_scheduled_at(value: int) -> Array[VschedPlain]:
	return find_by(&"scheduled_at", value)

func first_by_scheduled_at(value: int) -> VschedPlain:
	return first_by(&"scheduled_at", value)

func find_by_label(value: String) -> Array[VschedPlain]:
	return find_by(&"label", value)

func first_by_label(value: String) -> VschedPlain:
	return first_by(&"label", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VschedPlain)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VschedPlain, new_row as VschedPlain)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VschedPlain)
