# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VschedJob2Table extends _ModuleTable

signal inserted(row: VschedJob2)
signal updated(old_row: VschedJob2, new_row: VschedJob2)
signal deleted(row: VschedJob2)

var scheduled_id: VschedJob2ScheduledIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"job_2"
	scheduled_id = VschedJob2ScheduledIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VschedJob2]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VschedJob2] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VschedJob2]:
	var rows: Array = super(predicate)
	var typed_array: Array[VschedJob2] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VschedJob2:
	return super(predicate) as VschedJob2

func find_by(field: StringName, value: Variant) -> Array[VschedJob2]:
	var rows: Array = super(field, value)
	var typed_array: Array[VschedJob2] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VschedJob2:
	return super(field, value) as VschedJob2

func find_by_scheduled_id(value: int) -> Array[VschedJob2]:
	var row: VschedJob2 = scheduled_id.find(value)
	var result: Array[VschedJob2] = []
	if row != null:
		result.append(row)
	return result

func first_by_scheduled_id(value: int) -> VschedJob2:
	return scheduled_id.find(value)

func find_by_note(value: String) -> Array[VschedJob2]:
	return find_by(&"note", value)

func first_by_note(value: String) -> VschedJob2:
	return first_by(&"note", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VschedJob2)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VschedJob2, new_row as VschedJob2)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VschedJob2)
