# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VschedJobScheduledIdUniqueIndex extends _ModuleTableUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	_table_name = &"job"
	_field_name = &"scheduled_id"
	_read_primary_key_rows(p_local_db)

func find(col_val: int) -> VschedJob:
	return _find_by_primary_key(col_val)
