# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VschedJob2ScheduledIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, VschedJob2] = {}

func _init(p_local_db: LocalDatabase) -> void:
	_table_name = &"job_2"
	_field_name = &"scheduled_id"
	_connect_cache_to_db(_cache, p_local_db)

func find(col_val: int) -> VschedJob2:
	return _cache.get(col_val, null)
