# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VschedJobTable extends _ModuleTable

signal inserted(row: VschedJob)
signal updated(old_row: VschedJob, new_row: VschedJob)
signal deleted(row: VschedJob)

var scheduled_id: VschedJobScheduledIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"job"
	scheduled_id = VschedJobScheduledIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VschedJob]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VschedJob] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VschedJob]:
	var rows: Array = super(predicate)
	var typed_array: Array[VschedJob] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VschedJob:
	return super(predicate) as VschedJob

func find_by(field: StringName, value: Variant) -> Array[VschedJob]:
	var rows: Array = super(field, value)
	var typed_array: Array[VschedJob] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VschedJob:
	return super(field, value) as VschedJob

func find_by_scheduled_id(value: int) -> Array[VschedJob]:
	var row: VschedJob = scheduled_id.find(value)
	var result: Array[VschedJob] = []
	if row != null:
		result.append(row)
	return result

func first_by_scheduled_id(value: int) -> VschedJob:
	return scheduled_id.find(value)

func find_by_payload(value: String) -> Array[VschedJob]:
	return find_by(&"payload", value)

func first_by_payload(value: String) -> VschedJob:
	return first_by(&"payload", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VschedJob)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VschedJob, new_row as VschedJob)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VschedJob)
