# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name Vtypes2ThingTable extends _ModuleTable

var id: Vtypes2ThingIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"thing"
	id = Vtypes2ThingIdUniqueIndex.new(p_local_db)

func iter() -> Array[Vtypes2Thing]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[Vtypes2Thing] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[Vtypes2Thing]:
	var rows: Array = super(predicate)
	var typed_array: Array[Vtypes2Thing] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> Vtypes2Thing:
	return super(predicate) as Vtypes2Thing

func find_by(field: StringName, value: Variant) -> Array[Vtypes2Thing]:
	var rows: Array = super(field, value)
	var typed_array: Array[Vtypes2Thing] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> Vtypes2Thing:
	return super(field, value) as Vtypes2Thing
