# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name Vtypes2DurRowTable extends _ModuleTable

var id: Vtypes2DurRowIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"dur_row"
	id = Vtypes2DurRowIdUniqueIndex.new(p_local_db)

func iter() -> Array[Vtypes2DurRow]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[Vtypes2DurRow] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[Vtypes2DurRow]:
	var rows: Array = super(predicate)
	var typed_array: Array[Vtypes2DurRow] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> Vtypes2DurRow:
	return super(predicate) as Vtypes2DurRow

func find_by(field: StringName, value: Variant) -> Array[Vtypes2DurRow]:
	var rows: Array = super(field, value)
	var typed_array: Array[Vtypes2DurRow] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> Vtypes2DurRow:
	return super(field, value) as Vtypes2DurRow
