# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VbtreeModuleDb extends RefCounted

const table_names : Array[StringName] = [&"thing"]

var thing: VbtreeThingTable

func _init(p_local_db: LocalDatabase) -> void:
	thing = preload('user://golden_gen/vbtree/tables/vbtree_thing_table.gd').new(p_local_db)
