# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsumNote extends _ModuleTableType

const module_name : String = "Vsum"
const table_names: Array[StringName] = [&'note']
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"text": &"string" }

@export var text: String

## 0. text: String[br]
static func create(p_text: String) -> VsumNote:
	var result: VsumNote = VsumNote.new()
	result.text = p_text
	return result
