# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsumResRow extends _ModuleTableType

const module_name : String = "Vsum"
const table_names: Array[StringName] = [&'res_row']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"r": &"VsumResultI32String" }

@export var id: int
@export var r: VsumResultI32String

## 0. id: int[br]
## 1. r: VsumResultI32String[br]
static func create(p_id: int, p_r: VsumResultI32String) -> VsumResRow:
	var result: VsumResRow = VsumResRow.new()
	result.id = p_id
	result.r = p_r
	return result
