# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VprocenumKind extends RustEnum

enum Options {
	func_,
	class_,
	signal_,
	var_,
}

const ENUM_OPTIONS: Array[StringName] = [&'u32', &'string', &'', &'']

static func parse_enum_name(i: int) -> StringName:
	if i == 0:
		return &'func'
	elif i == 1:
		return &'class'
	elif i == 2:
		return &'signal'
	elif i == 3:
		return &'var'
	else:
		printerr("Enum does not have value for %d. This is out of bounds." % i)
		return &'Unknown'

func get_func() -> int:
	return data

func get_class_() -> String:
	return data

static func create(p_type: int, p_data: Variant = null) -> VprocenumKind:
	var result : VprocenumKind = VprocenumKind.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_func(_data: int) -> VprocenumKind:
	return create(Options.func_, _data)

static func create_class(_data: String) -> VprocenumKind:
	return create(Options.class_, _data)

static func create_signal() -> VprocenumKind:
	return create(Options.signal_)

static func create_var() -> VprocenumKind:
	return create(Options.var_)

