# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VprocenumKindRow extends _ModuleTableType

const module_name : String = "Vprocenum"
const table_names: Array[StringName] = [&'kind_row']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"kind": &"VprocenumKind" }

@export var id: int
@export var kind: VprocenumKind

## 0. id: int[br]
## 1. kind: VprocenumKind[br]
static func create(p_id: int, p_kind: VprocenumKind) -> VprocenumKindRow:
	var result: VprocenumKindRow = VprocenumKindRow.new()
	result.id = p_id
	result.kind = p_kind
	return result
