# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VprocenumKindRow extends _ModuleTableType

const module_name : String = "Vprocenum"
const table_names: Array[StringName] = [&'kind_row', &'script', &'table_names']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"kind": &"VprocenumKind", &"script_": &"string", &"count_": &"u32", &"resource_name_": &"string", &"create_": &"u32" }

@export var id: int
@export var kind: VprocenumKind
@export var script_: String
@export var count_: int
@export var resource_name_: String
@export var create_: int

## 0. id: int[br]
## 1. kind: VprocenumKind[br]
## 2. script_: String[br]
## 3. count_: int[br]
## 4. resource_name_: String[br]
## 5. create_: int[br]
static func create(p_id: int, p_kind: VprocenumKind, p_script_: String, p_count_: int, p_resource_name_: String, p_create_: int) -> VprocenumKindRow:
	var result: VprocenumKindRow = VprocenumKindRow.new()
	result.id = p_id
	result.kind = p_kind
	result.script_ = p_script_
	result.count_ = p_count_
	result.resource_name_ = p_resource_name_
	result.create_ = p_create_
	return result


## Whether two VprocenumKindRow values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: VprocenumKindRow, p_rhs: VprocenumKindRow) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.id != p_rhs.id:
		return false
	if not LocalDatabase._values_equal(p_lhs.kind, p_rhs.kind):
		return false
	if p_lhs.script_ != p_rhs.script_:
		return false
	if p_lhs.count_ != p_rhs.count_:
		return false
	if p_lhs.resource_name_ != p_rhs.resource_name_:
		return false
	if p_lhs.create_ != p_rhs.create_:
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: VprocenumKindRow = p_other as VprocenumKindRow
	if p_rhs == null:
		return false
	if self.id != p_rhs.id:
		return false
	if not LocalDatabase._values_equal(self.kind, p_rhs.kind):
		return false
	if self.script_ != p_rhs.script_:
		return false
	if self.count_ != p_rhs.count_:
		return false
	if self.resource_name_ != p_rhs.resource_name_:
		return false
	if self.create_ != p_rhs.create_:
		return false
	return true
