# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsubmodLibLibPoint extends Resource

const module_name : String = "Vsubmod"
const table_names: Array[StringName] = []
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"a": &"string", &"b": &"string" }

@export var a: String
@export var b: String

## 0. a: String[br]
## 1. b: String[br]
static func create(p_a: String, p_b: String) -> VsubmodLibLibPoint:
	var result: VsubmodLibLibPoint = VsubmodLibLibPoint.new()
	result.a = p_a
	result.b = p_b
	return result
