# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsubmodRootThing extends _ModuleTableType

const module_name : String = "Vsubmod"
const table_names: Array[StringName] = [&'root_thing']
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64" }

@export var id: int

## 0. id: int[br]
static func create(p_id: int) -> VsubmodRootThing:
	var result: VsubmodRootThing = VsubmodRootThing.new()
	result.id = p_id
	return result
