# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsubmodRootPoint extends Resource

const module_name : String = "Vsubmod"
const table_names: Array[StringName] = []
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"x": &"u64" }

@export var x: int

## 0. x: int[br]
static func create(p_x: int) -> VsubmodRootPoint:
	var result: VsubmodRootPoint = VsubmodRootPoint.new()
	result.x = p_x
	return result
