# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsubmodAuthAuthSession extends _ModuleTableType

const module_name : String = "Vsubmod"
const table_names: Array[StringName] = [&'auth.auth_session']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"token": &"string" }

@export var id: int
@export var token: String

## 0. id: int[br]
## 1. token: String[br]
static func create(p_id: int, p_token: String) -> VsubmodAuthAuthSession:
	var result: VsubmodAuthAuthSession = VsubmodAuthAuthSession.new()
	result.id = p_id
	result.token = p_token
	return result
