# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsubmodAuthAuthInsert extends Resource

const module_name : String = "Vsubmod"
const table_names: Array[StringName] = []
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"n": &"u64" }

@export var n: int

## 0. n: int[br]
static func create(p_n: int) -> VsubmodAuthAuthInsert:
	var result: VsubmodAuthAuthInsert = VsubmodAuthAuthInsert.new()
	result.n = p_n
	return result


## Whether two VsubmodAuthAuthInsert values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: VsubmodAuthAuthInsert, p_rhs: VsubmodAuthAuthInsert) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.n != p_rhs.n:
		return false
	return true
