# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsubmodLibLibPoint extends Resource

const module_name : String = "Vsubmod"
const table_names: Array[StringName] = []
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"a": &"string", &"b": &"string" }

@export var a: String
@export var b: String

## 0. a: String[br]
## 1. b: String[br]
static func create(p_a: String, p_b: String) -> VsubmodLibLibPoint:
	var result: VsubmodLibLibPoint = VsubmodLibLibPoint.new()
	result.a = p_a
	result.b = p_b
	return result


## Whether two VsubmodLibLibPoint values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: VsubmodLibLibPoint, p_rhs: VsubmodLibLibPoint) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.a != p_rhs.a:
		return false
	if p_lhs.b != p_rhs.b:
		return false
	return true
