# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsubmodRootThing extends _ModuleTableType

const module_name : String = "Vsubmod"
const table_names: Array[StringName] = [&'root_thing']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"point": &"VsubmodRootPoint" }

@export var id: int
@export var point: VsubmodRootPoint

## 0. id: int[br]
## 1. point: VsubmodRootPoint[br]
static func create(p_id: int, p_point: VsubmodRootPoint) -> VsubmodRootThing:
	var result: VsubmodRootThing = VsubmodRootThing.new()
	result.id = p_id
	result.point = p_point
	return result


## Whether two VsubmodRootThing values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: VsubmodRootThing, p_rhs: VsubmodRootThing) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.id != p_rhs.id:
		return false
	if not VsubmodRootPoint._eq(p_lhs.point, p_rhs.point):
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: VsubmodRootThing = p_other as VsubmodRootThing
	if p_rhs == null:
		return false
	if self.id != p_rhs.id:
		return false
	if not VsubmodRootPoint._eq(self.point, p_rhs.point):
		return false
	return true
