# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsubmodAuthAuthInsert extends Resource

const module_name : String = "Vsubmod"
const table_names: Array[StringName] = []
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"n": &"u64" }

@export var n: int

## 0. n: int[br]
static func create(p_n: int) -> VsubmodAuthAuthInsert:
	var result: VsubmodAuthAuthInsert = VsubmodAuthAuthInsert.new()
	result.n = p_n
	return result
