# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsubmodLibLibSecret extends _ModuleTableType

const module_name : String = "Vsubmod"
const table_names: Array[StringName] = [&'lib.lib_secret']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"secret": &"string" }

@export var id: int
@export var secret: String

## 0. id: int[br]
## 1. secret: String[br]
static func create(p_id: int, p_secret: String) -> VsubmodLibLibSecret:
	var result: VsubmodLibLibSecret = VsubmodLibLibSecret.new()
	result.id = p_id
	result.secret = p_secret
	return result
