# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsubmodLibLibData extends _ModuleTableType

const module_name : String = "Vsubmod"
const table_names: Array[StringName] = [&'lib.lib_data']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"point": &"VsubmodLibLibPoint" }

@export var id: int
@export var point: VsubmodLibLibPoint

## 0. id: int[br]
## 1. point: VsubmodLibLibPoint[br]
static func create(p_id: int, p_point: VsubmodLibLibPoint) -> VsubmodLibLibData:
	var result: VsubmodLibLibData = VsubmodLibLibData.new()
	result.id = p_id
	result.point = p_point
	return result
