# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsubmodLibLibData extends _ModuleTableType

const module_name : String = "Vsubmod"
const table_names: Array[StringName] = [&'lib.lib_data']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"point": &"VsubmodLibLibPoint" }

@export var id: int
@export var point: VsubmodLibLibPoint

## 0. id: int[br]
## 1. point: VsubmodLibLibPoint[br]
static func create(p_id: int, p_point: VsubmodLibLibPoint) -> VsubmodLibLibData:
	var result: VsubmodLibLibData = VsubmodLibLibData.new()
	result.id = p_id
	result.point = p_point
	return result


## Whether two VsubmodLibLibData values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: VsubmodLibLibData, p_rhs: VsubmodLibLibData) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.id != p_rhs.id:
		return false
	if not VsubmodLibLibPoint._eq(p_lhs.point, p_rhs.point):
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: VsubmodLibLibData = p_other as VsubmodLibLibData
	if p_rhs == null:
		return false
	if self.id != p_rhs.id:
		return false
	if not VsubmodLibLibPoint._eq(self.point, p_rhs.point):
		return false
	return true
