# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsubmodAuthBazBazItems extends _ModuleTableType

const module_name : String = "Vsubmod"
const table_names: Array[StringName] = [&'auth.baz.baz_items']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"item": &"VsubmodAuthBazBazItem" }

@export var id: int
@export var item: VsubmodAuthBazBazItem

## 0. id: int[br]
## 1. item: VsubmodAuthBazBazItem[br]
static func create(p_id: int, p_item: VsubmodAuthBazBazItem) -> VsubmodAuthBazBazItems:
	var result: VsubmodAuthBazBazItems = VsubmodAuthBazBazItems.new()
	result.id = p_id
	result.item = p_item
	return result
