# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsubmodAuthBazBazItem extends Resource

const module_name : String = "Vsubmod"
const table_names: Array[StringName] = []
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"label": &"string" }

@export var label: String

## 0. label: String[br]
static func create(p_label: String) -> VsubmodAuthBazBazItem:
	var result: VsubmodAuthBazBazItem = VsubmodAuthBazBazItem.new()
	result.label = p_label
	return result
