# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsubmodAuthAuthSession extends _ModuleTableType

const module_name : String = "Vsubmod"
const table_names: Array[StringName] = [&'auth.auth_session']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"token": &"string" }

@export var id: int
@export var token: String

## 0. id: int[br]
## 1. token: String[br]
static func create(p_id: int, p_token: String) -> VsubmodAuthAuthSession:
	var result: VsubmodAuthAuthSession = VsubmodAuthAuthSession.new()
	result.id = p_id
	result.token = p_token
	return result


## Whether two VsubmodAuthAuthSession values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: VsubmodAuthAuthSession, p_rhs: VsubmodAuthAuthSession) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.id != p_rhs.id:
		return false
	if p_lhs.token != p_rhs.token:
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: VsubmodAuthAuthSession = p_other as VsubmodAuthAuthSession
	if p_rhs == null:
		return false
	if self.id != p_rhs.id:
		return false
	if self.token != p_rhs.token:
		return false
	return true
