# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name Vtypes2ModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## 0. id: int [br]
## 1. micros: int [br]
func add_dur(id: int, micros: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('add_dur', [id, micros], [&'u64', &'i64'], &'')

## 0. v: int [br]
func add_seq(v: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('add_seq', [v], [&'u32'], &'')

## 0. id: int [br]
## 1. label: String [br]
func add_thing(id: int, label: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('add_thing', [id, label], [&'u64', &'string'], &'')

## 0. id: int [br]
func del_thing(id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('del_thing', [id], [&'u64'], &'')


func fail_reducer() -> SpacetimeDBReducerCall:
	return _client.call_reducer('fail_reducer', [], [], &'')

## 0. msg: String [br]
func log_event(msg: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('log_event', [msg], [&'string'], &'')

