# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VtypesOneI256Table extends _ModuleTable

signal inserted(row: VtypesOneI256)
signal updated(old_row: VtypesOneI256, new_row: VtypesOneI256)
signal deleted(row: VtypesOneI256)


func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"one_i_256"
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VtypesOneI256]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VtypesOneI256] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VtypesOneI256]:
	var rows: Array = super(predicate)
	var typed_array: Array[VtypesOneI256] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VtypesOneI256:
	return super(predicate) as VtypesOneI256

func find_by(field: StringName, value: Variant) -> Array[VtypesOneI256]:
	var rows: Array = super(field, value)
	var typed_array: Array[VtypesOneI256] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VtypesOneI256:
	return super(field, value) as VtypesOneI256

func find_by_n(value: PackedByteArray) -> Array[VtypesOneI256]:
	return find_by(&"n", value)

func first_by_n(value: PackedByteArray) -> VtypesOneI256:
	return first_by(&"n", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VtypesOneI256)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VtypesOneI256, new_row as VtypesOneI256)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VtypesOneI256)
