# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VtypesOneUuidTable extends _ModuleTable

signal inserted(row: VtypesOneUuid)
signal updated(old_row: VtypesOneUuid, new_row: VtypesOneUuid)
signal deleted(row: VtypesOneUuid)


func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"one_uuid"
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VtypesOneUuid]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VtypesOneUuid] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VtypesOneUuid]:
	var rows: Array = super(predicate)
	var typed_array: Array[VtypesOneUuid] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VtypesOneUuid:
	return super(predicate) as VtypesOneUuid

func find_by(field: StringName, value: Variant) -> Array[VtypesOneUuid]:
	var rows: Array = super(field, value)
	var typed_array: Array[VtypesOneUuid] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VtypesOneUuid:
	return super(field, value) as VtypesOneUuid

func find_by_u(value: PackedByteArray) -> Array[VtypesOneUuid]:
	return find_by(&"u", value)

func first_by_u(value: PackedByteArray) -> VtypesOneUuid:
	return first_by(&"u", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VtypesOneUuid)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VtypesOneUuid, new_row as VtypesOneUuid)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VtypesOneUuid)
