# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VtypesMyScheduleScheduledIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, VtypesMySchedule] = {}

func _init(p_local_db: LocalDatabase) -> void:
	_table_name = &"my_schedule"
	_field_name = &"scheduled_id"
	_connect_cache_to_db(_cache, p_local_db)

func find(col_val: int) -> VtypesMySchedule:
	return _cache.get(col_val, null)
