# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VreservedModuleDb extends RefCounted

const table_names : Array[StringName] = [&"alpha", &"signal"]

var alpha: VreservedAlphaTable
var signal_: VreservedSignalTable

func _init(p_local_db: LocalDatabase) -> void:
	alpha = preload('user://golden_gen/vreserved/tables/vreserved_alpha_table.gd').new(p_local_db)
	signal_ = preload('user://golden_gen/vreserved/tables/vreserved_signal_table.gd').new(p_local_db)
