# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VreservedModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## 0. id: int [br]
## 1. trait_: int [br]
func match_(id: int, trait_: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('match', [id, trait_], [&'u32', &'u32'], &'')

