# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VreservedModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## 0. id: int [br]
func match_(id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('match', [id], [&'u32'], &'')

