# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VsumModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## 0. text: String [br]
func add_note(text: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('add_note', [text], [&'string'], &'')

## 0. id: int [br]
## 1. ok: bool [br]
func add_res(id: int, ok: bool) -> SpacetimeDBReducerCall:
	return _client.call_reducer('add_res', [id, ok], [&'u64', &'bool'], &'')

## 0. id: int [br]
## 1. radius: int [br]
func add_shape(id: int, radius: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('add_shape', [id, radius], [&'u64', &'u32'], &'')

