# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VschedTypes

const Job = preload('user://golden_gen/vsched/types/vsched_job.gd')
const Job2 = preload('user://golden_gen/vsched/types/vsched_job_2.gd')
const Plain = preload('user://golden_gen/vsched/types/vsched_plain.gd')
