# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VschedModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## 0. id: int [br]
## 1. label: String [br]
func add_plain(id: int, label: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('add_plain', [id, label], [&'u64', &'string'], &'')

## 0. _row: VschedJob [br]
func run_job(_row: VschedJob) -> SpacetimeDBReducerCall:
	return _client.call_reducer('run_job', [_row], [&'VschedJob'], &'')

## 0. _row: VschedJob2 [br]
func run_job_2(_row: VschedJob2) -> SpacetimeDBReducerCall:
	return _client.call_reducer('run_job_2', [_row], [&'VschedJob2'], &'')

## 0. note: String [br]
func schedule_one(note: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('schedule_one', [note], [&'string'], &'')

## 0. s: ScheduleAt [br]
## 1. tag: String [br]
func take_sched(s: ScheduleAt, tag: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('take_sched', [s, tag], [&'scheduled_at', &'string'], &'')

