# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VschedModuleDb extends RefCounted

const table_names : Array[StringName] = [&"job", &"job_2", &"plain"]

var job: VschedJobTable
var job_2: VschedJob2Table
var plain: VschedPlainTable

func _init(p_local_db: LocalDatabase) -> void:
	job = preload('user://golden_gen/vsched/tables/vsched_job_table.gd').new(p_local_db)
	job_2 = preload('user://golden_gen/vsched/tables/vsched_job_2_table.gd').new(p_local_db)
	plain = preload('user://golden_gen/vsched/tables/vsched_plain_table.gd').new(p_local_db)
