# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VreservedThing extends _ModuleTableType

const module_name : String = "Vreserved"
const table_names: Array[StringName] = [&'alpha', &'signal']
const PRIMARY_KEY: StringName = &"func_"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"func_": &"u32", &"signal_": &"u32", &"class_": &"u32", &"trait_": &"u32", &"namespace_": &"u32" }

@export var func_: int
@export var signal_: int
@export var class_: int
@export var trait_: int
@export var namespace_: int

## 0. func_: int[br]
## 1. signal_: int[br]
## 2. class_: int[br]
## 3. trait_: int[br]
## 4. namespace_: int[br]
static func create(p_func_: int, p_signal_: int, p_class_: int, p_trait_: int, p_namespace_: int) -> VreservedThing:
	var result: VreservedThing = VreservedThing.new()
	result.func_ = p_func_
	result.signal_ = p_signal_
	result.class_ = p_class_
	result.trait_ = p_trait_
	result.namespace_ = p_namespace_
	return result


## Whether two VreservedThing values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: VreservedThing, p_rhs: VreservedThing) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.func_ != p_rhs.func_:
		return false
	if p_lhs.signal_ != p_rhs.signal_:
		return false
	if p_lhs.class_ != p_rhs.class_:
		return false
	if p_lhs.trait_ != p_rhs.trait_:
		return false
	if p_lhs.namespace_ != p_rhs.namespace_:
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: VreservedThing = p_other as VreservedThing
	if p_rhs == null:
		return false
	if self.func_ != p_rhs.func_:
		return false
	if self.signal_ != p_rhs.signal_:
		return false
	if self.class_ != p_rhs.class_:
		return false
	if self.trait_ != p_rhs.trait_:
		return false
	if self.namespace_ != p_rhs.namespace_:
		return false
	return true
