# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VsubmodTypes

const RootThing = preload('user://golden_gen/vsubmod/types/vsubmod_root_thing.gd')
const RootPoint = preload('user://golden_gen/vsubmod/types/vsubmod_root_point.gd')
const RootInsert = preload('user://golden_gen/vsubmod/types/vsubmod_root_insert.gd')
const LibLibData = preload('user://golden_gen/vsubmod/types/vsubmod_lib_lib_data.gd')
const LibLibPoint = preload('user://golden_gen/vsubmod/types/vsubmod_lib_lib_point.gd')
const LibLibSecret = preload('user://golden_gen/vsubmod/types/vsubmod_lib_lib_secret.gd')
const LibLibInsert = preload('user://golden_gen/vsubmod/types/vsubmod_lib_lib_insert.gd')
const AuthAuthSession = preload('user://golden_gen/vsubmod/types/vsubmod_auth_auth_session.gd')
const AuthAuthInsert = preload('user://golden_gen/vsubmod/types/vsubmod_auth_auth_insert.gd')
const AuthBazBazItems = preload('user://golden_gen/vsubmod/types/vsubmod_auth_baz_baz_items.gd')
const AuthBazBazItem = preload('user://golden_gen/vsubmod/types/vsubmod_auth_baz_baz_item.gd')
const AuthBazBazInsert = preload('user://golden_gen/vsubmod/types/vsubmod_auth_baz_baz_insert.gd')
