# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VsubmodModuleDb extends RefCounted

const table_names : Array[StringName] = [&"root_thing"]

var root_thing: VsubmodRootThingTable

func _init(p_local_db: LocalDatabase) -> void:
	root_thing = preload('user://golden_gen/vsubmod/tables/vsubmod_root_thing_table.gd').new(p_local_db)
