# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name Vtypes2EventLog extends _ModuleTableType

const module_name : String = "Vtypes2"
const table_names: Array[StringName] = [&'event_log']
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"msg": &"string" }

@export var msg: String

## 0. msg: String[br]
static func create(p_msg: String) -> Vtypes2EventLog:
	var result: Vtypes2EventLog = Vtypes2EventLog.new()
	result.msg = p_msg
	return result
