# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name Vtypes2SeqRow extends _ModuleTableType

const module_name : String = "Vtypes2"
const table_names: Array[StringName] = [&'seq_row']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"v": &"u32" }

@export var id: int
@export var v: int

## 0. id: int[br]
## 1. v: int[br]
static func create(p_id: int, p_v: int) -> Vtypes2SeqRow:
	var result: Vtypes2SeqRow = Vtypes2SeqRow.new()
	result.id = p_id
	result.v = p_v
	return result
