# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VsumTypes

const ResRow = preload('user://golden_gen/vsum/types/vsum_res_row.gd')
const ShapeRow = preload('user://golden_gen/vsum/types/vsum_shape_row.gd')
const Shape = preload('user://golden_gen/vsum/types/vsum_shape.gd')
const ResultI32String = preload('user://golden_gen/vsum/types/vsum_result_i_32_string.gd')
