# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VschedPlain extends _ModuleTableType

const module_name : String = "Vsched"
const table_names: Array[StringName] = [&'plain']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"scheduled_at": &"i64", &"label": &"string" }

@export var id: int
@export var scheduled_at: int
@export var label: String

## 0. id: int[br]
## 1. scheduled_at: int[br]
## 2. label: String[br]
static func create(p_id: int, p_scheduled_at: int, p_label: String) -> VschedPlain:
	var result: VschedPlain = VschedPlain.new()
	result.id = p_id
	result.scheduled_at = p_scheduled_at
	result.label = p_label
	return result
