# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VschedJob2 extends _ModuleTableType

const module_name : String = "Vsched"
const table_names: Array[StringName] = [&'job_2']
const PRIMARY_KEY: StringName = &"scheduled_id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"scheduled_id": &"u64", &"fire_at": &"scheduled_at", &"note": &"string" }

@export var scheduled_id: int
@export var fire_at: ScheduleAt
@export var note: String

## 0. scheduled_id: int[br]
## 1. fire_at: ScheduleAt[br]
## 2. note: String[br]
static func create(p_scheduled_id: int, p_fire_at: ScheduleAt, p_note: String) -> VschedJob2:
	var result: VschedJob2 = VschedJob2.new()
	result.scheduled_id = p_scheduled_id
	result.fire_at = p_fire_at
	result.note = p_note
	return result
