# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VschedJob extends _ModuleTableType

const module_name : String = "Vsched"
const table_names: Array[StringName] = [&'job']
const PRIMARY_KEY: StringName = &"scheduled_id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"scheduled_id": &"u64", &"scheduled_at": &"scheduled_at", &"payload": &"string" }

@export var scheduled_id: int
@export var scheduled_at: ScheduleAt
@export var payload: String

## 0. scheduled_id: int[br]
## 1. scheduled_at: ScheduleAt[br]
## 2. payload: String[br]
static func create(p_scheduled_id: int, p_scheduled_at: ScheduleAt, p_payload: String) -> VschedJob:
	var result: VschedJob = VschedJob.new()
	result.scheduled_id = p_scheduled_id
	result.scheduled_at = p_scheduled_at
	result.payload = p_payload
	return result
