# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name Vtypes2ModuleClient extends SpacetimeDBClient

var reducers: Vtypes2ModuleReducers
var procedures: Vtypes2ModuleProcedures
var db: Vtypes2ModuleDb

func _init() -> void:
	module_name = "Vtypes2"
	name = "Vtypes2Module"
	reducers = preload('user://golden_gen/vtypes2/module_vtypes_2_reducers.gd').new(self)
	procedures = preload('user://golden_gen/vtypes2/module_vtypes_2_procedures.gd').new(self)

func _init_db(p_local_db: LocalDatabase) -> void:
	db = preload('user://golden_gen/vtypes2/module_vtypes_2_db.gd').new(p_local_db)

## Subscribes to every table in this module with a single handle.
## Mirrors the official SDKs' subscribe-to-all-tables convenience.
func subscribe_all_tables() -> SpacetimeDBSubscription:
	if db == null:
		push_warning('subscribe_all_tables: db not initialized yet')
		return SpacetimeDBSubscription.fail(ERR_UNCONFIGURED)
	var queries: PackedStringArray = []
	for table_name: StringName in db.table_names:
		queries.append('SELECT * FROM %s' % table_name)
	return subscribe(queries)
