# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name Vtypes2Types

const DurRow = preload('user://golden_gen/vtypes2/types/vtypes_2_dur_row.gd')
const SeqRow = preload('user://golden_gen/vtypes2/types/vtypes_2_seq_row.gd')
const Thing = preload('user://golden_gen/vtypes2/types/vtypes_2_thing.gd')
