# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VprocenumTypes

const Kind = preload('user://golden_gen/vprocenum/types/vprocenum_kind.gd')
const KindRow = preload('user://golden_gen/vprocenum/types/vprocenum_kind_row.gd')
const ResultU32String = preload('user://golden_gen/vprocenum/types/vprocenum_result_u_32_string.gd')
