# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VprocenumModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client

func connect_row() -> SpacetimeDBReducerCall:
	return _client.call_reducer('connect_row', [], [], &'')

## 0. value: int [br]
func set_(value: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set', [value], [&'u32'], &'')

