# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VprocenumModuleDb extends RefCounted

const table_names : Array[StringName] = [&"kind_row"]

var kind_row: VprocenumKindRowTable

func _init(p_local_db: LocalDatabase) -> void:
	kind_row = preload('user://golden_gen/vprocenum/tables/vprocenum_kind_row_table.gd').new(p_local_db)
