# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VprocenumModuleProcedures extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## Returns: VprocenumResultU32String [br]
## 0. func_: int [br]
## 1. signal_: String [br]
func class_(func_: int, signal_: String) -> SpacetimeDBProcedureCall:
	return _client.call_procedure('class', [func_, signal_], [&'u32', &'string'], &'VprocenumResultU32String')

## Returns:  [br]
func match_() -> SpacetimeDBProcedureCall:
	return _client.call_procedure('match', [], [], &'')

## Returns:  [br]
## 0. what: int [br]
func notification_(what: int) -> SpacetimeDBProcedureCall:
	return _client.call_procedure('notification', [what], [&'i32'], &'')

