# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VsumShape extends RustEnum

enum Options {
	circle,
	square,
	nothing,
}

const ENUM_OPTIONS: Array[StringName] = [&'u32', &'u32', &'']

static func parse_enum_name(i: int) -> StringName:
	if i == 0:
		return &'circle'
	elif i == 1:
		return &'square'
	elif i == 2:
		return &'nothing'
	else:
		printerr("Enum does not have value for %d. This is out of bounds." % i)
		return &'Unknown'

func get_circle() -> int:
	return data

func get_square() -> int:
	return data

static func create(p_type: int, p_data: Variant = null) -> VsumShape:
	var result : VsumShape = VsumShape.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_circle(_data: int) -> VsumShape:
	return create(Options.circle, _data)

static func create_square(_data: int) -> VsumShape:
	return create(Options.square, _data)

static func create_nothing() -> VsumShape:
	return create(Options.nothing)

