# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsumShapeRow extends _ModuleTableType

const module_name : String = "Vsum"
const table_names: Array[StringName] = [&'shape_row']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"shape": &"VsumShape" }

@export var id: int
@export var shape: VsumShape

## 0. id: int[br]
## 1. shape: VsumShape[br]
static func create(p_id: int, p_shape: VsumShape) -> VsumShapeRow:
	var result: VsumShapeRow = VsumShapeRow.new()
	result.id = p_id
	result.shape = p_shape
	return result
