# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VsumResRow extends _ModuleTableType

const module_name : String = "Vsum"
const table_names: Array[StringName] = [&'res_row']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"r": &"VsumResultI32String" }

@export var id: int
@export var r: VsumResultI32String

## 0. id: int[br]
## 1. r: VsumResultI32String[br]
static func create(p_id: int, p_r: VsumResultI32String) -> VsumResRow:
	var result: VsumResRow = VsumResRow.new()
	result.id = p_id
	result.r = p_r
	return result


## Whether two VsumResRow values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: VsumResRow, p_rhs: VsumResRow) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.id != p_rhs.id:
		return false
	if not LocalDatabase._values_equal(p_lhs.r, p_rhs.r):
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: VsumResRow = p_other as VsumResRow
	if p_rhs == null:
		return false
	if self.id != p_rhs.id:
		return false
	if not LocalDatabase._values_equal(self.r, p_rhs.r):
		return false
	return true
