# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VviewModuleDb extends RefCounted

const table_names : Array[StringName] = [&"damage", &"damage_mirror", &"dupes", &"my_thing", &"thing", &"thing_briefs", &"thing_count", &"things_over"]

var damage: VviewDamageTable
var damage_mirror: VviewDamageMirrorTable
var dupes: VviewDupesTable
var my_thing: VviewMyThingTable
var thing: VviewThingTable
var thing_briefs: VviewThingBriefsTable
var thing_count: VviewThingCountTable
var things_over: VviewThingsOverTable

func _init(p_local_db: LocalDatabase) -> void:
	damage = preload('user://golden_gen/vview/tables/vview_damage_table.gd').new(p_local_db)
	damage_mirror = preload('user://golden_gen/vview/tables/vview_damage_mirror_table.gd').new(p_local_db)
	dupes = preload('user://golden_gen/vview/tables/vview_dupes_table.gd').new(p_local_db)
	my_thing = preload('user://golden_gen/vview/tables/vview_my_thing_table.gd').new(p_local_db)
	thing = preload('user://golden_gen/vview/tables/vview_thing_table.gd').new(p_local_db)
	thing_briefs = preload('user://golden_gen/vview/tables/vview_thing_briefs_table.gd').new(p_local_db)
	thing_count = preload('user://golden_gen/vview/tables/vview_thing_count_table.gd').new(p_local_db)
	things_over = preload('user://golden_gen/vview/tables/vview_things_over_table.gd').new(p_local_db)
