# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VviewModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## 0. id: int [br]
## 1. score: int [br]
## 2. label: String [br]
func add_thing(id: int, score: int, label: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('add_thing', [id, score, label], [&'u64', &'u32', &'string'], &'')

## 0. id: int [br]
func del_thing(id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('del_thing', [id], [&'u64'], &'')

## 0. id: int [br]
## 1. score: int [br]
func set_score(id: int, score: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_score', [id, score], [&'u64', &'u32'], &'')

