# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VviewTypes

const Thing = preload('user://golden_gen/vview/types/vview_thing.gd')
const ThingBrief = preload('user://golden_gen/vview/types/vview_thing_brief.gd')
const ThingCount = preload('user://golden_gen/vview/types/vview_thing_count.gd')
