# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VeventThingTable extends _ModuleTable

signal inserted(row: VeventThing)
signal updated(old_row: VeventThing, new_row: VeventThing)
signal deleted(row: VeventThing)

var id: VeventThingIdUniqueIndex
var score: VeventThingScoreBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"thing"
	id = VeventThingIdUniqueIndex.new(p_local_db)
	score = VeventThingScoreBTreeIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VeventThing]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VeventThing] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VeventThing]:
	var rows: Array = super(predicate)
	var typed_array: Array[VeventThing] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VeventThing:
	return super(predicate) as VeventThing

func find_by(field: StringName, value: Variant) -> Array[VeventThing]:
	var rows: Array = super(field, value)
	var typed_array: Array[VeventThing] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VeventThing:
	return super(field, value) as VeventThing

func find_by_id(value: int) -> Array[VeventThing]:
	var row: VeventThing = id.find(value)
	var result: Array[VeventThing] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VeventThing:
	return id.find(value)

func find_by_score(value: int) -> Array[VeventThing]:
	return score.filter(value)

func first_by_score(value: int) -> VeventThing:
	return score._first_row(value) as VeventThing

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VeventThing)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VeventThing, new_row as VeventThing)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VeventThing)
