# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VeventDamageTable extends _ModuleTable

signal inserted(row: VeventDamage)
signal updated(old_row: VeventDamage, new_row: VeventDamage)
signal deleted(row: VeventDamage)


func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"damage"
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VeventDamage]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VeventDamage] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VeventDamage]:
	var rows: Array = super(predicate)
	var typed_array: Array[VeventDamage] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VeventDamage:
	return super(predicate) as VeventDamage

func find_by(field: StringName, value: Variant) -> Array[VeventDamage]:
	var rows: Array = super(field, value)
	var typed_array: Array[VeventDamage] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VeventDamage:
	return super(field, value) as VeventDamage

func find_by_id(value: int) -> Array[VeventDamage]:
	return find_by(&"id", value)

func first_by_id(value: int) -> VeventDamage:
	return first_by(&"id", value)

func find_by_target(value: int) -> Array[VeventDamage]:
	return find_by(&"target", value)

func first_by_target(value: int) -> VeventDamage:
	return first_by(&"target", value)

func find_by_amount(value: int) -> Array[VeventDamage]:
	return find_by(&"amount", value)

func first_by_amount(value: int) -> VeventDamage:
	return first_by(&"amount", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VeventDamage)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VeventDamage, new_row as VeventDamage)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VeventDamage)
