# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VtypesModuleDb extends RefCounted

const table_names : Array[StringName] = [&"my_schedule", &"one_i_128", &"one_i_256", &"one_u_128", &"one_u_256", &"one_uuid"]

var my_schedule: VtypesMyScheduleTable
var one_i_128: VtypesOneI128Table
var one_i_256: VtypesOneI256Table
var one_u_128: VtypesOneU128Table
var one_u_256: VtypesOneU256Table
var one_uuid: VtypesOneUuidTable

func _init(p_local_db: LocalDatabase) -> void:
	my_schedule = preload('user://golden_gen/vtypes/tables/vtypes_my_schedule_table.gd').new(p_local_db)
	one_i_128 = preload('user://golden_gen/vtypes/tables/vtypes_one_i_128_table.gd').new(p_local_db)
	one_i_256 = preload('user://golden_gen/vtypes/tables/vtypes_one_i_256_table.gd').new(p_local_db)
	one_u_128 = preload('user://golden_gen/vtypes/tables/vtypes_one_u_128_table.gd').new(p_local_db)
	one_u_256 = preload('user://golden_gen/vtypes/tables/vtypes_one_u_256_table.gd').new(p_local_db)
	one_uuid = preload('user://golden_gen/vtypes/tables/vtypes_one_uuid_table.gd').new(p_local_db)
