# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VtypesOneI128 extends _ModuleTableType

const module_name : String = "Vtypes"
const table_names: Array[StringName] = [&'one_i_128']
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"n": &"i128" }

@export var n: PackedByteArray

## 0. n: PackedByteArray[br]
static func create(p_n: PackedByteArray) -> VtypesOneI128:
	var result: VtypesOneI128 = VtypesOneI128.new()
	result.n = p_n
	return result
