# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VtypesMySchedule extends _ModuleTableType

const module_name : String = "Vtypes"
const table_names: Array[StringName] = [&'my_schedule']
const PRIMARY_KEY: StringName = &"scheduled_id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"scheduled_id": &"u64", &"scheduled_at": &"scheduled_at" }

@export var scheduled_id: int
@export var scheduled_at: ScheduleAt

## 0. scheduled_id: int[br]
## 1. scheduled_at: ScheduleAt[br]
static func create(p_scheduled_id: int, p_scheduled_at: ScheduleAt) -> VtypesMySchedule:
	var result: VtypesMySchedule = VtypesMySchedule.new()
	result.scheduled_id = p_scheduled_id
	result.scheduled_at = p_scheduled_at
	return result
