# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VtypesOneU128 extends _ModuleTableType

const module_name : String = "Vtypes"
const table_names: Array[StringName] = [&'one_u_128']
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"n": &"u128" }

@export var n: PackedByteArray

## 0. n: PackedByteArray[br]
static func create(p_n: PackedByteArray) -> VtypesOneU128:
	var result: VtypesOneU128 = VtypesOneU128.new()
	result.n = p_n
	return result
