# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VeventModuleDb extends RefCounted

const table_names : Array[StringName] = [&"damage", &"thing"]

var damage: VeventDamageTable
var thing: VeventThingTable

func _init(p_local_db: LocalDatabase) -> void:
	damage = preload('user://golden_gen/vevent/tables/vevent_damage_table.gd').new(p_local_db)
	thing = preload('user://golden_gen/vevent/tables/vevent_thing_table.gd').new(p_local_db)
