# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name Vtypes2EventLogTable extends _ModuleTable

signal inserted(row: Vtypes2EventLog)
signal updated(old_row: Vtypes2EventLog, new_row: Vtypes2EventLog)
signal deleted(row: Vtypes2EventLog)


func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"event_log"
	_relay_row_signals()

func iter() -> Array[Vtypes2EventLog]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[Vtypes2EventLog] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[Vtypes2EventLog]:
	var rows: Array = super(predicate)
	var typed_array: Array[Vtypes2EventLog] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> Vtypes2EventLog:
	return super(predicate) as Vtypes2EventLog

func find_by(field: StringName, value: Variant) -> Array[Vtypes2EventLog]:
	var rows: Array = super(field, value)
	var typed_array: Array[Vtypes2EventLog] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> Vtypes2EventLog:
	return super(field, value) as Vtypes2EventLog

func find_by_msg(value: String) -> Array[Vtypes2EventLog]:
	return find_by(&"msg", value)

func first_by_msg(value: String) -> Vtypes2EventLog:
	return first_by(&"msg", value)
