# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VtypesMyScheduleTable extends _ModuleTable

var scheduled_id: VtypesMyScheduleScheduledIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"my_schedule"
	scheduled_id = VtypesMyScheduleScheduledIdUniqueIndex.new(p_local_db)

func iter() -> Array[VtypesMySchedule]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VtypesMySchedule] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VtypesMySchedule]:
	var rows: Array = super(predicate)
	var typed_array: Array[VtypesMySchedule] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VtypesMySchedule:
	return super(predicate) as VtypesMySchedule

func find_by(field: StringName, value: Variant) -> Array[VtypesMySchedule]:
	var rows: Array = super(field, value)
	var typed_array: Array[VtypesMySchedule] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VtypesMySchedule:
	return super(field, value) as VtypesMySchedule
