# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VtypesMyScheduleTable extends _ModuleTable

signal inserted(row: VtypesMySchedule)
signal updated(old_row: VtypesMySchedule, new_row: VtypesMySchedule)
signal deleted(row: VtypesMySchedule)

var scheduled_id: VtypesMyScheduleScheduledIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"my_schedule"
	scheduled_id = VtypesMyScheduleScheduledIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VtypesMySchedule]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VtypesMySchedule] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VtypesMySchedule]:
	var rows: Array = super(predicate)
	var typed_array: Array[VtypesMySchedule] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VtypesMySchedule:
	return super(predicate) as VtypesMySchedule

func find_by(field: StringName, value: Variant) -> Array[VtypesMySchedule]:
	var rows: Array = super(field, value)
	var typed_array: Array[VtypesMySchedule] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VtypesMySchedule:
	return super(field, value) as VtypesMySchedule

func find_by_scheduled_id(value: int) -> Array[VtypesMySchedule]:
	var row: VtypesMySchedule = scheduled_id.find(value)
	var result: Array[VtypesMySchedule] = []
	if row != null:
		result.append(row)
	return result

func first_by_scheduled_id(value: int) -> VtypesMySchedule:
	return scheduled_id.find(value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VtypesMySchedule)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VtypesMySchedule, new_row as VtypesMySchedule)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VtypesMySchedule)
