# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VtypesOneU256Table extends _ModuleTable


func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"one_u_256"

func iter() -> Array[VtypesOneU256]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VtypesOneU256] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VtypesOneU256]:
	var rows: Array = super(predicate)
	var typed_array: Array[VtypesOneU256] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VtypesOneU256:
	return super(predicate) as VtypesOneU256

func find_by(field: StringName, value: Variant) -> Array[VtypesOneU256]:
	var rows: Array = super(field, value)
	var typed_array: Array[VtypesOneU256] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VtypesOneU256:
	return super(field, value) as VtypesOneU256
