# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VtypesOneUuidTable extends _ModuleTable


func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"one_uuid"

func iter() -> Array[VtypesOneUuid]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VtypesOneUuid] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VtypesOneUuid]:
	var rows: Array = super(predicate)
	var typed_array: Array[VtypesOneUuid] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VtypesOneUuid:
	return super(predicate) as VtypesOneUuid

func find_by(field: StringName, value: Variant) -> Array[VtypesOneUuid]:
	var rows: Array = super(field, value)
	var typed_array: Array[VtypesOneUuid] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VtypesOneUuid:
	return super(field, value) as VtypesOneUuid
