# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VviewThingBriefsTable extends _ModuleTable

signal inserted(row: VviewThingBrief)
signal updated(old_row: VviewThingBrief, new_row: VviewThingBrief)
signal deleted(row: VviewThingBrief)


func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"thing_briefs"
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VviewThingBrief]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VviewThingBrief] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VviewThingBrief]:
	var rows: Array = super(predicate)
	var typed_array: Array[VviewThingBrief] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VviewThingBrief:
	return super(predicate) as VviewThingBrief

func find_by(field: StringName, value: Variant) -> Array[VviewThingBrief]:
	var rows: Array = super(field, value)
	var typed_array: Array[VviewThingBrief] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VviewThingBrief:
	return super(field, value) as VviewThingBrief

func find_by_thing_id(value: int) -> Array[VviewThingBrief]:
	return find_by(&"thing_id", value)

func first_by_thing_id(value: int) -> VviewThingBrief:
	return first_by(&"thing_id", value)

func find_by_label(value: String) -> Array[VviewThingBrief]:
	return find_by(&"label", value)

func first_by_label(value: String) -> VviewThingBrief:
	return first_by(&"label", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VviewThingBrief)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VviewThingBrief, new_row as VviewThingBrief)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VviewThingBrief)
