# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VviewThingCountTable extends _ModuleTable

signal inserted(row: VviewThingCount)
signal updated(old_row: VviewThingCount, new_row: VviewThingCount)
signal deleted(row: VviewThingCount)


func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"thing_count"
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VviewThingCount]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VviewThingCount] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VviewThingCount]:
	var rows: Array = super(predicate)
	var typed_array: Array[VviewThingCount] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VviewThingCount:
	return super(predicate) as VviewThingCount

func find_by(field: StringName, value: Variant) -> Array[VviewThingCount]:
	var rows: Array = super(field, value)
	var typed_array: Array[VviewThingCount] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VviewThingCount:
	return super(field, value) as VviewThingCount

func find_by_count_(value: int) -> Array[VviewThingCount]:
	return find_by(&"count_", value)

func first_by_count_(value: int) -> VviewThingCount:
	return first_by(&"count_", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VviewThingCount)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VviewThingCount, new_row as VviewThingCount)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VviewThingCount)
