# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VviewDamageTable extends _ModuleTable

signal inserted(row: VviewDamage)
signal updated(old_row: VviewDamage, new_row: VviewDamage)
signal deleted(row: VviewDamage)


func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"damage"
	_relay_row_signals()

func iter() -> Array[VviewDamage]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VviewDamage] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VviewDamage]:
	var rows: Array = super(predicate)
	var typed_array: Array[VviewDamage] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VviewDamage:
	return super(predicate) as VviewDamage

func find_by(field: StringName, value: Variant) -> Array[VviewDamage]:
	var rows: Array = super(field, value)
	var typed_array: Array[VviewDamage] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VviewDamage:
	return super(field, value) as VviewDamage

func find_by_target(value: int) -> Array[VviewDamage]:
	return find_by(&"target", value)

func first_by_target(value: int) -> VviewDamage:
	return first_by(&"target", value)

func find_by_amount(value: int) -> Array[VviewDamage]:
	return find_by(&"amount", value)

func first_by_amount(value: int) -> VviewDamage:
	return first_by(&"amount", value)
