# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VviewDupesTable extends _ModuleTable

signal inserted(row: VviewThing)
signal updated(old_row: VviewThing, new_row: VviewThing)
signal deleted(row: VviewThing)


func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"dupes"
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VviewThing]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VviewThing] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VviewThing]:
	var rows: Array = super(predicate)
	var typed_array: Array[VviewThing] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VviewThing:
	return super(predicate) as VviewThing

func find_by(field: StringName, value: Variant) -> Array[VviewThing]:
	var rows: Array = super(field, value)
	var typed_array: Array[VviewThing] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VviewThing:
	return super(field, value) as VviewThing

func find_by_id(value: int) -> Array[VviewThing]:
	return find_by(&"id", value)

func first_by_id(value: int) -> VviewThing:
	return first_by(&"id", value)

func find_by_score(value: int) -> Array[VviewThing]:
	return find_by(&"score", value)

func first_by_score(value: int) -> VviewThing:
	return first_by(&"score", value)

func find_by_label(value: String) -> Array[VviewThing]:
	return find_by(&"label", value)

func first_by_label(value: String) -> VviewThing:
	return first_by(&"label", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VviewThing)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VviewThing, new_row as VviewThing)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VviewThing)
