# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VbtreeThingTable extends _ModuleTable

signal inserted(row: VbtreeThing)
signal updated(old_row: VbtreeThing, new_row: VbtreeThing)
signal deleted(row: VbtreeThing)

var id: VbtreeThingIdUniqueIndex
var score: VbtreeThingScoreBTreeIndex
var owner: VbtreeThingOwnerBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"thing"
	id = VbtreeThingIdUniqueIndex.new(p_local_db)
	score = VbtreeThingScoreBTreeIndex.new(p_local_db)
	owner = VbtreeThingOwnerBTreeIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VbtreeThing]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VbtreeThing] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VbtreeThing]:
	var rows: Array = super(predicate)
	var typed_array: Array[VbtreeThing] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VbtreeThing:
	return super(predicate) as VbtreeThing

func find_by(field: StringName, value: Variant) -> Array[VbtreeThing]:
	var rows: Array = super(field, value)
	var typed_array: Array[VbtreeThing] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VbtreeThing:
	return super(field, value) as VbtreeThing

func find_by_id(value: int) -> Array[VbtreeThing]:
	var row: VbtreeThing = id.find(value)
	var result: Array[VbtreeThing] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VbtreeThing:
	return id.find(value)

func find_by_score(value: int) -> Array[VbtreeThing]:
	return score.filter(value)

func first_by_score(value: int) -> VbtreeThing:
	return score._first_row(value) as VbtreeThing

func find_by_owner(value: PackedByteArray) -> Array[VbtreeThing]:
	return owner.filter(value)

func first_by_owner(value: PackedByteArray) -> VbtreeThing:
	return owner._first_row(value) as VbtreeThing

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VbtreeThing)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VbtreeThing, new_row as VbtreeThing)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VbtreeThing)
