# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VbtreeThingScoreBTreeIndex extends _ModuleTableBTreeIndex

var _cache: Dictionary[int, Array] = {}

func _init(p_local_db: LocalDatabase) -> void:
	_table_name = &"thing"
	_field_name = &"score"
	_connect_cache_to_db(_cache, p_local_db)

func filter(col_val: int) -> Array[VbtreeThing]:
	var typed_array: Array[VbtreeThing] = []
	typed_array.assign(_cache.get(col_val, []))
	return typed_array

func filter_range(from_val: int, to_val: int) -> Array[VbtreeThing]:
	var typed_array: Array[VbtreeThing] = []
	typed_array.assign(_range_rows(from_val, to_val))
	return typed_array
