# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VsumResRowTable extends _ModuleTable

var id: VsumResRowIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"res_row"
	id = VsumResRowIdUniqueIndex.new(p_local_db)

func iter() -> Array[VsumResRow]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VsumResRow] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VsumResRow]:
	var rows: Array = super(predicate)
	var typed_array: Array[VsumResRow] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VsumResRow:
	return super(predicate) as VsumResRow

func find_by(field: StringName, value: Variant) -> Array[VsumResRow]:
	var rows: Array = super(field, value)
	var typed_array: Array[VsumResRow] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VsumResRow:
	return super(field, value) as VsumResRow
