# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VsumResRowTable extends _ModuleTable

signal inserted(row: VsumResRow)
signal updated(old_row: VsumResRow, new_row: VsumResRow)
signal deleted(row: VsumResRow)

var id: VsumResRowIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"res_row"
	id = VsumResRowIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VsumResRow]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VsumResRow] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VsumResRow]:
	var rows: Array = super(predicate)
	var typed_array: Array[VsumResRow] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VsumResRow:
	return super(predicate) as VsumResRow

func find_by(field: StringName, value: Variant) -> Array[VsumResRow]:
	var rows: Array = super(field, value)
	var typed_array: Array[VsumResRow] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VsumResRow:
	return super(field, value) as VsumResRow

func find_by_id(value: int) -> Array[VsumResRow]:
	return find_by(&"id", value)

func first_by_id(value: int) -> VsumResRow:
	return first_by(&"id", value)

func find_by_r(value: VsumResultI32String) -> Array[VsumResRow]:
	return find_by(&"r", value)

func first_by_r(value: VsumResultI32String) -> VsumResRow:
	return first_by(&"r", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VsumResRow)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VsumResRow, new_row as VsumResRow)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VsumResRow)
