# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VsumShapeRowTable extends _ModuleTable

var id: VsumShapeRowIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"shape_row"
	id = VsumShapeRowIdUniqueIndex.new(p_local_db)

func iter() -> Array[VsumShapeRow]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VsumShapeRow] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VsumShapeRow]:
	var rows: Array = super(predicate)
	var typed_array: Array[VsumShapeRow] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VsumShapeRow:
	return super(predicate) as VsumShapeRow

func find_by(field: StringName, value: Variant) -> Array[VsumShapeRow]:
	var rows: Array = super(field, value)
	var typed_array: Array[VsumShapeRow] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VsumShapeRow:
	return super(field, value) as VsumShapeRow
