# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VbtreeThing extends _ModuleTableType

const module_name : String = "Vbtree"
const table_names: Array[StringName] = [&'thing']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u32", &"score": &"u32", &"owner": &"u256" }

@export var id: int
@export var score: int
@export var owner: PackedByteArray

## 0. id: int[br]
## 1. score: int[br]
## 2. owner: PackedByteArray[br]
static func create(p_id: int, p_score: int, p_owner: PackedByteArray) -> VbtreeThing:
	var result: VbtreeThing = VbtreeThing.new()
	result.id = p_id
	result.score = p_score
	result.owner = p_owner
	return result
