# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
extends Node
#SpacetimeDB Autoload

var Blackholio: BlackholioModuleClient
var MyModule: MyModuleModuleClient
var Vtypes: VtypesModuleClient

func _init() -> void:
	Blackholio = preload('user://golden_gen/autoload/module_blackholio_client.gd').new()
	add_child(Blackholio)
	MyModule = preload('user://golden_gen/autoload/module_my_module_client.gd').new()
	add_child(MyModule)
	Vtypes = preload('user://golden_gen/autoload/module_vtypes_client.gd').new()
	add_child(Vtypes)
