# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name BlackholioFood extends _ModuleTableType

const module_name : String = "Blackholio"
const table_names: Array[StringName] = [&'food']
const PRIMARY_KEY: StringName = &"entity_id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"entity_id": &"i32" }

@export var entity_id: int

## 0. entity_id: int[br]
static func create(p_entity_id: int) -> BlackholioFood:
	var result: BlackholioFood = BlackholioFood.new()
	result.entity_id = p_entity_id
	return result


## Whether two BlackholioFood values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: BlackholioFood, p_rhs: BlackholioFood) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.entity_id != p_rhs.entity_id:
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: BlackholioFood = p_other as BlackholioFood
	if p_rhs == null:
		return false
	if self.entity_id != p_rhs.entity_id:
		return false
	return true
