# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name BlackholioProbeKind extends RustEnum

enum Options {
	unit,
	scalar,
	text,
}

const ENUM_OPTIONS: Array[StringName] = [&'', &'i32', &'string']

static func parse_enum_name(i: int) -> StringName:
	if i == 0:
		return &'unit'
	elif i == 1:
		return &'scalar'
	elif i == 2:
		return &'text'
	else:
		printerr("Enum does not have value for %d. This is out of bounds." % i)
		return &'Unknown'

func get_scalar() -> int:
	return data

func get_text() -> String:
	return data

static func create(p_type: int, p_data: Variant = null) -> BlackholioProbeKind:
	var result : BlackholioProbeKind = BlackholioProbeKind.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_unit() -> BlackholioProbeKind:
	return create(Options.unit)

static func create_scalar(_data: int) -> BlackholioProbeKind:
	return create(Options.scalar, _data)

static func create_text(_data: String) -> BlackholioProbeKind:
	return create(Options.text, _data)

