# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name BlackholioProbeRow extends _ModuleTableType

const module_name : String = "Blackholio"
const table_names: Array[StringName] = [&'probe_row']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"i32", &"maybe_text": &"string", &"maybe_count": &"i32", &"kind": &"BlackholioProbeKind", &"wide_unsigned": &"u128", &"widest_unsigned": &"u256", &"wide_signed": &"i128", &"who": &"identity" }

@export var id: int
@export var maybe_text: Option ## Option of String
@export var maybe_count: Option ## Option of int
@export var kind: BlackholioProbeKind
@export var wide_unsigned: PackedByteArray
@export var widest_unsigned: PackedByteArray
@export var wide_signed: PackedByteArray
@export var who: PackedByteArray

## 0. id: int[br]
## 1. maybe_text: Option of String[br]
## 2. maybe_count: Option of int[br]
## 3. kind: BlackholioProbeKind[br]
## 4. wide_unsigned: PackedByteArray[br]
## 5. widest_unsigned: PackedByteArray[br]
## 6. wide_signed: PackedByteArray[br]
## 7. who: PackedByteArray[br]
static func create(p_id: int, p_maybe_text: Option, p_maybe_count: Option, p_kind: BlackholioProbeKind, p_wide_unsigned: PackedByteArray, p_widest_unsigned: PackedByteArray, p_wide_signed: PackedByteArray, p_who: PackedByteArray) -> BlackholioProbeRow:
	var result: BlackholioProbeRow = BlackholioProbeRow.new()
	result.id = p_id
	result.maybe_text = p_maybe_text
	result.maybe_count = p_maybe_count
	result.kind = p_kind
	result.wide_unsigned = p_wide_unsigned
	result.widest_unsigned = p_widest_unsigned
	result.wide_signed = p_wide_signed
	result.who = p_who
	return result
