# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name BlackholioPlayer extends _ModuleTableType

const module_name : String = "Blackholio"
const table_names: Array[StringName] = [&'player']
const PRIMARY_KEY: StringName = &"identity"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"identity": &"identity", &"player_id": &"i32", &"name": &"string" }

@export var identity: PackedByteArray
@export var player_id: int
@export var name: String

## 0. identity: PackedByteArray[br]
## 1. player_id: int[br]
## 2. name: String[br]
static func create(p_identity: PackedByteArray, p_player_id: int, p_name: String) -> BlackholioPlayer:
	var result: BlackholioPlayer = BlackholioPlayer.new()
	result.identity = p_identity
	result.player_id = p_player_id
	result.name = p_name
	return result


## Whether two BlackholioPlayer values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: BlackholioPlayer, p_rhs: BlackholioPlayer) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.identity != p_rhs.identity:
		return false
	if p_lhs.player_id != p_rhs.player_id:
		return false
	if p_lhs.name != p_rhs.name:
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: BlackholioPlayer = p_other as BlackholioPlayer
	if p_rhs == null:
		return false
	if self.identity != p_rhs.identity:
		return false
	if self.player_id != p_rhs.player_id:
		return false
	if self.name != p_rhs.name:
		return false
	return true
