# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name BlackholioConsumeEntityTimer extends _ModuleTableType

const module_name : String = "Blackholio"
const table_names: Array[StringName] = []
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"scheduled_id": &"u64", &"scheduled_at": &"scheduled_at", &"consumed_entity_id": &"i32", &"consumer_entity_id": &"i32" }

@export var scheduled_id: int
@export var scheduled_at: ScheduleAt
@export var consumed_entity_id: int
@export var consumer_entity_id: int

## 0. scheduled_id: int[br]
## 1. scheduled_at: ScheduleAt[br]
## 2. consumed_entity_id: int[br]
## 3. consumer_entity_id: int[br]
static func create(p_scheduled_id: int, p_scheduled_at: ScheduleAt, p_consumed_entity_id: int, p_consumer_entity_id: int) -> BlackholioConsumeEntityTimer:
	var result: BlackholioConsumeEntityTimer = BlackholioConsumeEntityTimer.new()
	result.scheduled_id = p_scheduled_id
	result.scheduled_at = p_scheduled_at
	result.consumed_entity_id = p_consumed_entity_id
	result.consumer_entity_id = p_consumer_entity_id
	return result


## Whether two BlackholioConsumeEntityTimer values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: BlackholioConsumeEntityTimer, p_rhs: BlackholioConsumeEntityTimer) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.scheduled_id != p_rhs.scheduled_id:
		return false
	if not LocalDatabase._values_equal(p_lhs.scheduled_at, p_rhs.scheduled_at):
		return false
	if p_lhs.consumed_entity_id != p_rhs.consumed_entity_id:
		return false
	if p_lhs.consumer_entity_id != p_rhs.consumer_entity_id:
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: BlackholioConsumeEntityTimer = p_other as BlackholioConsumeEntityTimer
	if p_rhs == null:
		return false
	if self.scheduled_id != p_rhs.scheduled_id:
		return false
	if not LocalDatabase._values_equal(self.scheduled_at, p_rhs.scheduled_at):
		return false
	if self.consumed_entity_id != p_rhs.consumed_entity_id:
		return false
	if self.consumer_entity_id != p_rhs.consumer_entity_id:
		return false
	return true
