# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name BlackholioCircle extends _ModuleTableType

const module_name : String = "Blackholio"
const table_names: Array[StringName] = [&'circle']
const PRIMARY_KEY: StringName = &"entity_id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"entity_id": &"i32", &"player_id": &"i32", &"direction": &"BlackholioDbVector2", &"speed": &"f32", &"last_split_time": &"i64" }

@export var entity_id: int
@export var player_id: int
@export var direction: BlackholioDbVector2
@export var speed: float
@export var last_split_time: int

## 0. entity_id: int[br]
## 1. player_id: int[br]
## 2. direction: BlackholioDbVector2[br]
## 3. speed: float[br]
## 4. last_split_time: int[br]
static func create(p_entity_id: int, p_player_id: int, p_direction: BlackholioDbVector2, p_speed: float, p_last_split_time: int) -> BlackholioCircle:
	var result: BlackholioCircle = BlackholioCircle.new()
	result.entity_id = p_entity_id
	result.player_id = p_player_id
	result.direction = p_direction
	result.speed = p_speed
	result.last_split_time = p_last_split_time
	return result


## Whether two BlackholioCircle values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: BlackholioCircle, p_rhs: BlackholioCircle) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.entity_id != p_rhs.entity_id:
		return false
	if p_lhs.player_id != p_rhs.player_id:
		return false
	if not BlackholioDbVector2._eq(p_lhs.direction, p_rhs.direction):
		return false
	if p_lhs.speed != p_rhs.speed and not (is_nan(p_lhs.speed) and is_nan(p_rhs.speed)):
		return false
	if p_lhs.last_split_time != p_rhs.last_split_time:
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: BlackholioCircle = p_other as BlackholioCircle
	if p_rhs == null:
		return false
	if self.entity_id != p_rhs.entity_id:
		return false
	if self.player_id != p_rhs.player_id:
		return false
	if not BlackholioDbVector2._eq(self.direction, p_rhs.direction):
		return false
	if self.speed != p_rhs.speed and not (is_nan(self.speed) and is_nan(p_rhs.speed)):
		return false
	if self.last_split_time != p_rhs.last_split_time:
		return false
	return true
