# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name BlackholioConfig extends _ModuleTableType

const module_name : String = "Blackholio"
const table_names: Array[StringName] = [&'config']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"i32", &"world_size": &"i64" }

@export var id: int
@export var world_size: int

## 0. id: int[br]
## 1. world_size: int[br]
static func create(p_id: int, p_world_size: int) -> BlackholioConfig:
	var result: BlackholioConfig = BlackholioConfig.new()
	result.id = p_id
	result.world_size = p_world_size
	return result


## Whether two BlackholioConfig values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: BlackholioConfig, p_rhs: BlackholioConfig) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.id != p_rhs.id:
		return false
	if p_lhs.world_size != p_rhs.world_size:
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: BlackholioConfig = p_other as BlackholioConfig
	if p_rhs == null:
		return false
	if self.id != p_rhs.id:
		return false
	if self.world_size != p_rhs.world_size:
		return false
	return true
