# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name BlackholioDbVector2 extends Resource

const module_name : String = "Blackholio"
const table_names: Array[StringName] = []
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"x": &"f32", &"y": &"f32" }

@export var x: float
@export var y: float

## 0. x: float[br]
## 1. y: float[br]
static func create(p_x: float, p_y: float) -> BlackholioDbVector2:
	var result: BlackholioDbVector2 = BlackholioDbVector2.new()
	result.x = p_x
	result.y = p_y
	return result


## Whether two BlackholioDbVector2 values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: BlackholioDbVector2, p_rhs: BlackholioDbVector2) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.x != p_rhs.x and not (is_nan(p_lhs.x) and is_nan(p_rhs.x)):
		return false
	if p_lhs.y != p_rhs.y and not (is_nan(p_lhs.y) and is_nan(p_rhs.y)):
		return false
	return true
