# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name BlackholioCircleDecayTimer extends _ModuleTableType

const module_name : String = "Blackholio"
const table_names: Array[StringName] = []
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"scheduled_id": &"u64", &"scheduled_at": &"scheduled_at" }

@export var scheduled_id: int
@export var scheduled_at: ScheduleAt

## 0. scheduled_id: int[br]
## 1. scheduled_at: ScheduleAt[br]
static func create(p_scheduled_id: int, p_scheduled_at: ScheduleAt) -> BlackholioCircleDecayTimer:
	var result: BlackholioCircleDecayTimer = BlackholioCircleDecayTimer.new()
	result.scheduled_id = p_scheduled_id
	result.scheduled_at = p_scheduled_at
	return result


## Whether two BlackholioCircleDecayTimer values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: BlackholioCircleDecayTimer, p_rhs: BlackholioCircleDecayTimer) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.scheduled_id != p_rhs.scheduled_id:
		return false
	if not LocalDatabase._values_equal(p_lhs.scheduled_at, p_rhs.scheduled_at):
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: BlackholioCircleDecayTimer = p_other as BlackholioCircleDecayTimer
	if p_rhs == null:
		return false
	if self.scheduled_id != p_rhs.scheduled_id:
		return false
	if not LocalDatabase._values_equal(self.scheduled_at, p_rhs.scheduled_at):
		return false
	return true
