# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name BlackholioProbeRow extends _ModuleTableType

const module_name : String = "Blackholio"
const table_names: Array[StringName] = [&'probe_row']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"i32", &"maybe_text": &"string", &"maybe_count": &"i32", &"kind": &"BlackholioProbeKind", &"wide_unsigned": &"u128", &"widest_unsigned": &"u256", &"wide_signed": &"i128", &"who": &"identity", &"numbers": &"i32", &"words": &"string", &"points": &"BlackholioDbVector2" }

@export var id: int
@export var maybe_text: Option ## Option of String
@export var maybe_count: Option ## Option of int
@export var kind: BlackholioProbeKind
@export var wide_unsigned: PackedByteArray
@export var widest_unsigned: PackedByteArray
@export var wide_signed: PackedByteArray
@export var who: PackedByteArray
@export var numbers: Array[int] ## Array of int
@export var words: Array[String] ## Array of String
@export var points: Array[BlackholioDbVector2] ## Array of BlackholioDbVector2

## 0. id: int[br]
## 1. maybe_text: Option of String[br]
## 2. maybe_count: Option of int[br]
## 3. kind: BlackholioProbeKind[br]
## 4. wide_unsigned: PackedByteArray[br]
## 5. widest_unsigned: PackedByteArray[br]
## 6. wide_signed: PackedByteArray[br]
## 7. who: PackedByteArray[br]
## 8. numbers: Array of int[br]
## 9. words: Array of String[br]
## 10. points: Array of BlackholioDbVector2[br]
static func create(p_id: int, p_maybe_text: Option, p_maybe_count: Option, p_kind: BlackholioProbeKind, p_wide_unsigned: PackedByteArray, p_widest_unsigned: PackedByteArray, p_wide_signed: PackedByteArray, p_who: PackedByteArray, p_numbers: Array[int], p_words: Array[String], p_points: Array[BlackholioDbVector2]) -> BlackholioProbeRow:
	var result: BlackholioProbeRow = BlackholioProbeRow.new()
	result.id = p_id
	result.maybe_text = p_maybe_text
	result.maybe_count = p_maybe_count
	result.kind = p_kind
	result.wide_unsigned = p_wide_unsigned
	result.widest_unsigned = p_widest_unsigned
	result.wide_signed = p_wide_signed
	result.who = p_who
	result.numbers = p_numbers
	result.words = p_words
	result.points = p_points
	return result


## Whether two BlackholioProbeRow values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: BlackholioProbeRow, p_rhs: BlackholioProbeRow) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.id != p_rhs.id:
		return false
	if not LocalDatabase._values_equal(p_lhs.maybe_text, p_rhs.maybe_text):
		return false
	if not LocalDatabase._values_equal(p_lhs.maybe_count, p_rhs.maybe_count):
		return false
	if not LocalDatabase._values_equal(p_lhs.kind, p_rhs.kind):
		return false
	if p_lhs.wide_unsigned != p_rhs.wide_unsigned:
		return false
	if p_lhs.widest_unsigned != p_rhs.widest_unsigned:
		return false
	if p_lhs.wide_signed != p_rhs.wide_signed:
		return false
	if p_lhs.who != p_rhs.who:
		return false
	if not LocalDatabase._values_equal(p_lhs.numbers, p_rhs.numbers):
		return false
	if not LocalDatabase._values_equal(p_lhs.words, p_rhs.words):
		return false
	if not LocalDatabase._values_equal(p_lhs.points, p_rhs.points):
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: BlackholioProbeRow = p_other as BlackholioProbeRow
	if p_rhs == null:
		return false
	if self.id != p_rhs.id:
		return false
	if not LocalDatabase._values_equal(self.maybe_text, p_rhs.maybe_text):
		return false
	if not LocalDatabase._values_equal(self.maybe_count, p_rhs.maybe_count):
		return false
	if not LocalDatabase._values_equal(self.kind, p_rhs.kind):
		return false
	if self.wide_unsigned != p_rhs.wide_unsigned:
		return false
	if self.widest_unsigned != p_rhs.widest_unsigned:
		return false
	if self.wide_signed != p_rhs.wide_signed:
		return false
	if self.who != p_rhs.who:
		return false
	if not LocalDatabase._values_equal(self.numbers, p_rhs.numbers):
		return false
	if not LocalDatabase._values_equal(self.words, p_rhs.words):
		return false
	if not LocalDatabase._values_equal(self.points, p_rhs.points):
		return false
	return true
