# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name MainTestTableDatatypes extends _ModuleTableType

const module_name : String = "Main"
const table_names: Array[String] = ['test_table_datatypes', 'test_anonymous_all_types', 'test_first_type_row', 'test_u_32_at_30']

@export var t_u_64: int
@export var t_u_8: int
@export var t_u_16: int
@export var t_u_32: int
@export var t_u_128: PackedByteArray
@export var t_f_32: float
@export var t_f_64: float
@export var t_i_8: int
@export var t_i_16: int
@export var t_i_32: int
@export var t_i_64: int
@export var t_string: String
@export var t_vec_string: Array[String]
@export var t_vec_u_8: Array[int]
@export var t_opt_string: Option ## Option of String
@export var t_opt_u_64: Option ## Option of int
@export var t_test_enum: MainModuleClient.Types.TestEnum
@export var t_test_enum_vec: Array[MainModuleClient.Types.TestEnum]
@export var t_test_enum_option: Option ## Option of MainModuleClient.Types.TestEnum
@export var t_test_type: MainTestType
@export var t_test_type_vec: Array[MainTestType]
@export var t_test_type_option: Option ## Option of MainTestType

func _init() -> void:
	_reset_metadata()

func _reset_metadata() -> void:
	# Clear old metadata
	for key : StringName in get_meta_list():
		set_meta(key, null)

	set_meta('primary_key', 't_u_64')
	set_meta('bsatn_type_t_u_64', &'u64')
	set_meta('bsatn_type_t_u_8', &'u8')
	set_meta('bsatn_type_t_u_16', &'u16')
	set_meta('bsatn_type_t_u_32', &'u32')
	set_meta('bsatn_type_t_u_128', &'u128')
	set_meta('bsatn_type_t_f_32', &'f32')
	set_meta('bsatn_type_t_f_64', &'f64')
	set_meta('bsatn_type_t_i_8', &'i8')
	set_meta('bsatn_type_t_i_16', &'i16')
	set_meta('bsatn_type_t_i_32', &'i32')
	set_meta('bsatn_type_t_i_64', &'i64')
	set_meta('bsatn_type_t_string', &'string')
	set_meta('bsatn_type_t_vec_string', &'string')
	set_meta('bsatn_type_t_vec_u_8', &'u8')
	set_meta('underlying_type_t_opt_string', &'String')
	set_meta('bsatn_type_t_opt_string', &'string')
	set_meta('underlying_type_t_opt_u_64', &'int')
	set_meta('bsatn_type_t_opt_u_64', &'u64')
	set_meta('bsatn_type_t_test_enum', &'u8')
	set_meta('bsatn_type_t_test_enum_vec', &'u8')
	set_meta('underlying_type_t_test_enum_option', &'MainModuleClient.Types.TestEnum')
	set_meta('bsatn_type_t_test_enum_option', &'u8')
	set_meta('bsatn_type_t_test_type', &'MainTestType')
	set_meta('bsatn_type_t_test_type_vec', &'MainTestType')
	set_meta('underlying_type_t_test_type_option', &'MainTestType')
	set_meta('bsatn_type_t_test_type_option', &'MainTestType')

## 0. t_u_64: int[br]
## 1. t_u_8: int[br]
## 2. t_u_16: int[br]
## 3. t_u_32: int[br]
## 4. t_u_128: PackedByteArray[br]
## 5. t_f_32: float[br]
## 6. t_f_64: float[br]
## 7. t_i_8: int[br]
## 8. t_i_16: int[br]
## 9. t_i_32: int[br]
## 10. t_i_64: int[br]
## 11. t_string: String[br]
## 12. t_vec_string: Array of String[br]
## 13. t_vec_u_8: Array of int[br]
## 14. t_opt_string: Option of String[br]
## 15. t_opt_u_64: Option of int[br]
## 16. t_test_enum: MainModuleClient.Types.TestEnum[br]
## 17. t_test_enum_vec: Array of MainModuleClient.Types.TestEnum[br]
## 18. t_test_enum_option: Option of MainModuleClient.Types.TestEnum[br]
## 19. t_test_type: MainTestType[br]
## 20. t_test_type_vec: Array of MainTestType[br]
## 21. t_test_type_option: Option of MainTestType[br]
static func create(p_t_u_64: int, p_t_u_8: int, p_t_u_16: int, p_t_u_32: int, p_t_u_128: PackedByteArray, p_t_f_32: float, p_t_f_64: float, p_t_i_8: int, p_t_i_16: int, p_t_i_32: int, p_t_i_64: int, p_t_string: String, p_t_vec_string: Array[String], p_t_vec_u_8: Array[int], p_t_opt_string: Option, p_t_opt_u_64: Option, p_t_test_enum: MainModuleClient.Types.TestEnum, p_t_test_enum_vec: Array[MainModuleClient.Types.TestEnum], p_t_test_enum_option: Option, p_t_test_type: MainTestType, p_t_test_type_vec: Array[MainTestType], p_t_test_type_option: Option) -> MainTestTableDatatypes:
	var result: MainTestTableDatatypes = MainTestTableDatatypes.new()
	result.t_u_64 = p_t_u_64
	result.t_u_8 = p_t_u_8
	result.t_u_16 = p_t_u_16
	result.t_u_32 = p_t_u_32
	result.t_u_128 = p_t_u_128
	result.t_f_32 = p_t_f_32
	result.t_f_64 = p_t_f_64
	result.t_i_8 = p_t_i_8
	result.t_i_16 = p_t_i_16
	result.t_i_32 = p_t_i_32
	result.t_i_64 = p_t_i_64
	result.t_string = p_t_string
	result.t_vec_string = p_t_vec_string
	result.t_vec_u_8 = p_t_vec_u_8
	result.t_opt_string = p_t_opt_string
	result.t_opt_u_64 = p_t_opt_u_64
	result.t_test_enum = p_t_test_enum
	result.t_test_enum_vec = p_t_test_enum_vec
	result.t_test_enum_option = p_t_test_enum_option
	result.t_test_type = p_t_test_type
	result.t_test_type_vec = p_t_test_type_vec
	result.t_test_type_option = p_t_test_type_option
	return result
