# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name MainViewType extends _ModuleTableType

const module_name : String = "Main"
const table_names: Array[String] = ['test_no_pk_table', 'test_no_pk_option', 'test_no_pk_query', 'test_no_pk_vec']

@export var row: int
@export var name: String

func _init() -> void:
	_reset_metadata()

func _reset_metadata() -> void:
	# Clear old metadata
	for key : StringName in get_meta_list():
		set_meta(key, null)

	set_meta('primary_key', '')
	set_meta('bsatn_type_row', &'u64')
	set_meta('bsatn_type_name', &'string')

## 0. row: int[br]
## 1. name: String[br]
static func create(p_row: int, p_name: String) -> MainViewType:
	var result: MainViewType = MainViewType.new()
	result.row = p_row
	result.name = p_name
	return result
