# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainTestNestedEnum extends RustEnum

enum Options {
	ok,
	okEmpty,
	err,
	internalError,
	test,
}

func _init() -> void:
	_reset_metadata()

func _reset_metadata() -> void:
	# Clear old metadata
	for key : StringName in get_meta_list():
		set_meta(key, null)

	set_meta('enum_options', [&'u64', &'', &'vec_u8', &'string', &'MainTestScheduledTable'])
	set_meta('bsatn_enum_type', &'MainTestNestedEnum')

static func parse_enum_name(i: int) -> String:
	match i:
		0: return &'ok'
		1: return &'okEmpty'
		2: return &'err'
		3: return &'internalError'
		4: return &'test'
		_:
			printerr("Enum does not have value for %d. This is out of bounds." % i)
			return &'Unknown'

func get_ok() -> int:
	return data

func get_err() -> Array[int]:
	return data

func get_internal_error() -> String:
	return data

func get_test() -> MainTestScheduledTable:
	return data

static func create(p_type: int, p_data: Variant = null) -> MainTestNestedEnum:
	var result : MainTestNestedEnum = MainTestNestedEnum.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_ok(_data: int) -> MainTestNestedEnum:
	return create(Options.ok, _data)

static func create_ok_empty() -> MainTestNestedEnum:
	return create(Options.okEmpty)

static func create_err(_data: Array[int]) -> MainTestNestedEnum:
	return create(Options.err, _data)

static func create_internal_error(_data: String) -> MainTestNestedEnum:
	return create(Options.internalError, _data)

static func create_test(_data: MainTestScheduledTable) -> MainTestNestedEnum:
	return create(Options.test, _data)

