# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VviewThingCount extends _ModuleTableType

const module_name : String = "Vview"
const table_names: Array[StringName] = [&'thing_count']
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"count_": &"u64" }

@export var count_: int

## 0. count_: int[br]
static func create(p_count_: int) -> VviewThingCount:
	var result: VviewThingCount = VviewThingCount.new()
	result.count_ = p_count_
	return result


## Whether two VviewThingCount values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: VviewThingCount, p_rhs: VviewThingCount) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.count_ != p_rhs.count_:
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: VviewThingCount = p_other as VviewThingCount
	if p_rhs == null:
		return false
	if self.count_ != p_rhs.count_:
		return false
	return true
