# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VviewThingBrief extends _ModuleTableType

const module_name : String = "Vview"
const table_names: Array[StringName] = [&'thing_briefs']
const PRIMARY_KEY: StringName = &"thing_id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"thing_id": &"u64", &"label": &"string" }

@export var thing_id: int
@export var label: String

## 0. thing_id: int[br]
## 1. label: String[br]
static func create(p_thing_id: int, p_label: String) -> VviewThingBrief:
	var result: VviewThingBrief = VviewThingBrief.new()
	result.thing_id = p_thing_id
	result.label = p_label
	return result


## Whether two VviewThingBrief values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: VviewThingBrief, p_rhs: VviewThingBrief) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.thing_id != p_rhs.thing_id:
		return false
	if p_lhs.label != p_rhs.label:
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: VviewThingBrief = p_other as VviewThingBrief
	if p_rhs == null:
		return false
	if self.thing_id != p_rhs.thing_id:
		return false
	if self.label != p_rhs.label:
		return false
	return true
