# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VviewThing extends _ModuleTableType

const module_name : String = "Vview"
const table_names: Array[StringName] = [&'dupes', &'my_thing', &'thing', &'things_over']
const PRIMARY_KEY_BY_TABLE: Dictionary[StringName, StringName] = { &"dupes": &"", &"my_thing": &"", &"thing": &"id", &"things_over": &"" }
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"score": &"u32", &"label": &"string" }

@export var id: int
@export var score: int
@export var label: String

## 0. id: int[br]
## 1. score: int[br]
## 2. label: String[br]
static func create(p_id: int, p_score: int, p_label: String) -> VviewThing:
	var result: VviewThing = VviewThing.new()
	result.id = p_id
	result.score = p_score
	result.label = p_label
	return result
