# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VviewThingBrief extends _ModuleTableType

const module_name : String = "Vview"
const table_names: Array[StringName] = [&'thing_briefs']
const PRIMARY_KEY: StringName = &"thing_id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"thing_id": &"u64", &"label": &"string" }

@export var thing_id: int
@export var label: String

## 0. thing_id: int[br]
## 1. label: String[br]
static func create(p_thing_id: int, p_label: String) -> VviewThingBrief:
	var result: VviewThingBrief = VviewThingBrief.new()
	result.thing_id = p_thing_id
	result.label = p_label
	return result
