# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VviewThing extends _ModuleTableType

const module_name : String = "Vview"
const table_names: Array[StringName] = [&'dupes', &'my_thing', &'thing', &'things_over']
const PRIMARY_KEY_BY_TABLE: Dictionary[StringName, StringName] = { &"dupes": &"", &"my_thing": &"", &"thing": &"id", &"things_over": &"" }
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"score": &"u32", &"label": &"string" }

@export var id: int
@export var score: int
@export var label: String

## 0. id: int[br]
## 1. score: int[br]
## 2. label: String[br]
static func create(p_id: int, p_score: int, p_label: String) -> VviewThing:
	var result: VviewThing = VviewThing.new()
	result.id = p_id
	result.score = p_score
	result.label = p_label
	return result


## Whether two VviewThing values are equal column by column, as LocalDatabase compares rows.
static func _eq(p_lhs: VviewThing, p_rhs: VviewThing) -> bool:
	if p_lhs == null or p_rhs == null:
		return p_lhs == p_rhs
	if p_lhs.id != p_rhs.id:
		return false
	if p_lhs.score != p_rhs.score:
		return false
	if p_lhs.label != p_rhs.label:
		return false
	return true


func _row_eq(p_other: _ModuleTableType, _p_columns: Array[StringName]) -> bool:
	var p_rhs: VviewThing = p_other as VviewThing
	if p_rhs == null:
		return false
	if self.id != p_rhs.id:
		return false
	if self.score != p_rhs.score:
		return false
	if self.label != p_rhs.label:
		return false
	return true
