# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VviewThingCount extends _ModuleTableType

const module_name : String = "Vview"
const table_names: Array[StringName] = [&'thing_count']
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"count_": &"u64" }

@export var count_: int

## 0. count_: int[br]
static func create(p_count_: int) -> VviewThingCount:
	var result: VviewThingCount = VviewThingCount.new()
	result.count_ = p_count_
	return result
