# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VviewDamage extends _ModuleTableType

const module_name : String = "Vview"
const table_names: Array[StringName] = [&'damage', &'damage_mirror']
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"target": &"u64", &"amount": &"u32" }

@export var target: int
@export var amount: int

## 0. target: int[br]
## 1. amount: int[br]
static func create(p_target: int, p_amount: int) -> VviewDamage:
	var result: VviewDamage = VviewDamage.new()
	result.target = p_target
	result.amount = p_amount
	return result
