# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VprocenumKindRowCountBTreeIndex extends _ModuleTableBTreeIndex

var _cache: Dictionary[int, Array] = {}

func _init(p_local_db: LocalDatabase) -> void:
	_table_name = &"kind_row"
	_field_name = &"count_"
	_connect_cache_to_db(_cache, p_local_db)

func filter(col_val: int) -> Array[VprocenumKindRow]:
	var typed_array: Array[VprocenumKindRow] = []
	typed_array.assign(_cache.get(col_val, []))
	return typed_array

func filter_range(from_val: int, to_val: int) -> Array[VprocenumKindRow]:
	var typed_array: Array[VprocenumKindRow] = []
	typed_array.assign(_range_rows(from_val, to_val))
	return typed_array

func filter_gte(col_val: int) -> Array[VprocenumKindRow]:
	var typed_array: Array[VprocenumKindRow] = []
	typed_array.assign(_gte_rows(col_val))
	return typed_array

func filter_gt(col_val: int) -> Array[VprocenumKindRow]:
	var typed_array: Array[VprocenumKindRow] = []
	typed_array.assign(_gt_rows(col_val))
	return typed_array

func filter_lte(col_val: int) -> Array[VprocenumKindRow]:
	var typed_array: Array[VprocenumKindRow] = []
	typed_array.assign(_lte_rows(col_val))
	return typed_array

func filter_lt(col_val: int) -> Array[VprocenumKindRow]:
	var typed_array: Array[VprocenumKindRow] = []
	typed_array.assign(_lt_rows(col_val))
	return typed_array
