# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VprocenumKindRowTable extends _ModuleTable

signal inserted(row: VprocenumKindRow)
signal updated(old_row: VprocenumKindRow, new_row: VprocenumKindRow)
signal deleted(row: VprocenumKindRow)

var id: VprocenumKindRowIdUniqueIndex
var count_: VprocenumKindRowCountBTreeIndex
var resource_name_: VprocenumKindRowResourceNameBTreeIndex
var script_: VprocenumKindRowScriptBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"kind_row"
	id = VprocenumKindRowIdUniqueIndex.new(p_local_db)
	count_ = VprocenumKindRowCountBTreeIndex.new(p_local_db)
	resource_name_ = VprocenumKindRowResourceNameBTreeIndex.new(p_local_db)
	script_ = VprocenumKindRowScriptBTreeIndex.new(p_local_db)
	_relay_row_signals()

func iter() -> Array[VprocenumKindRow]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VprocenumKindRow] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VprocenumKindRow]:
	var rows: Array = super(predicate)
	var typed_array: Array[VprocenumKindRow] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VprocenumKindRow:
	return super(predicate) as VprocenumKindRow

func find_by(field: StringName, value: Variant) -> Array[VprocenumKindRow]:
	var rows: Array = super(field, value)
	var typed_array: Array[VprocenumKindRow] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VprocenumKindRow:
	return super(field, value) as VprocenumKindRow

func find_by_id(value: int) -> Array[VprocenumKindRow]:
	var row: VprocenumKindRow = id.find(value)
	var result: Array[VprocenumKindRow] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VprocenumKindRow:
	return id.find(value)

func find_by_script_(value: String) -> Array[VprocenumKindRow]:
	return script_.filter(value)

func first_by_script_(value: String) -> VprocenumKindRow:
	return script_._first_row(value) as VprocenumKindRow

func find_by_count_(value: int) -> Array[VprocenumKindRow]:
	return count_.filter(value)

func first_by_count_(value: int) -> VprocenumKindRow:
	return count_._first_row(value) as VprocenumKindRow

func find_by_resource_name_(value: String) -> Array[VprocenumKindRow]:
	return resource_name_.filter(value)

func first_by_resource_name_(value: String) -> VprocenumKindRow:
	return resource_name_._first_row(value) as VprocenumKindRow

func find_by_create_(value: int) -> Array[VprocenumKindRow]:
	return find_by(&"create_", value)

func first_by_create_(value: int) -> VprocenumKindRow:
	return first_by(&"create_", value)
