# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VprocenumKindRowTable extends _ModuleTable

signal inserted(row: VprocenumKindRow)
signal updated(old_row: VprocenumKindRow, new_row: VprocenumKindRow)
signal deleted(row: VprocenumKindRow)

var id: VprocenumKindRowIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"kind_row"
	id = VprocenumKindRowIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VprocenumKindRow]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VprocenumKindRow] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VprocenumKindRow]:
	var rows: Array = super(predicate)
	var typed_array: Array[VprocenumKindRow] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VprocenumKindRow:
	return super(predicate) as VprocenumKindRow

func find_by(field: StringName, value: Variant) -> Array[VprocenumKindRow]:
	var rows: Array = super(field, value)
	var typed_array: Array[VprocenumKindRow] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VprocenumKindRow:
	return super(field, value) as VprocenumKindRow

func find_by_id(value: int) -> Array[VprocenumKindRow]:
	var row: VprocenumKindRow = id.find(value)
	var result: Array[VprocenumKindRow] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VprocenumKindRow:
	return id.find(value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VprocenumKindRow)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VprocenumKindRow, new_row as VprocenumKindRow)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VprocenumKindRow)
