# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VprocenumScriptTable extends _ModuleTable

signal inserted(row: VprocenumKindRow)
signal updated(old_row: VprocenumKindRow, new_row: VprocenumKindRow)
signal deleted(row: VprocenumKindRow)


func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"script"
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VprocenumKindRow]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VprocenumKindRow] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VprocenumKindRow]:
	var rows: Array = super(predicate)
	var typed_array: Array[VprocenumKindRow] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VprocenumKindRow:
	return super(predicate) as VprocenumKindRow

func find_by(field: StringName, value: Variant) -> Array[VprocenumKindRow]:
	var rows: Array = super(field, value)
	var typed_array: Array[VprocenumKindRow] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VprocenumKindRow:
	return super(field, value) as VprocenumKindRow

func find_by_id(value: int) -> Array[VprocenumKindRow]:
	return find_by(&"id", value)

func first_by_id(value: int) -> VprocenumKindRow:
	return first_by(&"id", value)

func find_by_script_(value: String) -> Array[VprocenumKindRow]:
	return find_by(&"script_", value)

func first_by_script_(value: String) -> VprocenumKindRow:
	return first_by(&"script_", value)

func find_by_count_(value: int) -> Array[VprocenumKindRow]:
	return find_by(&"count_", value)

func first_by_count_(value: int) -> VprocenumKindRow:
	return first_by(&"count_", value)

func find_by_resource_name_(value: String) -> Array[VprocenumKindRow]:
	return find_by(&"resource_name_", value)

func first_by_resource_name_(value: String) -> VprocenumKindRow:
	return first_by(&"resource_name_", value)

func find_by_create_(value: int) -> Array[VprocenumKindRow]:
	return find_by(&"create_", value)

func first_by_create_(value: int) -> VprocenumKindRow:
	return first_by(&"create_", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VprocenumKindRow)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VprocenumKindRow, new_row as VprocenumKindRow)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VprocenumKindRow)
