class_name SpacetimeCodegen
extends Resource

const REQUIRED_FOLDERS_IN_CODEGEN_FOLDER: Array[String] = ["tables", "types"]
const OPTION_CLASS_NAME := "Option"
const AUTOGENERATED_COMMENT := "# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS\n" +
"# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.\n"

const GDSCRIPT_RESERVED_WORDS: Array[String] = [
	"if",
	"elif",
	"else",
	"for",
	"while",
	"match",
	"break",
	"continue",
	"pass",
	"return",
	"class",
	"class_name",
	"extends",
	"is",
	"as",
	"self",
	"signal",
	"func",
	"static",
	"const",
	"enum",
	"var",
	"breakpoint",
	"preload",
	"await",
	"yield",
	"assert",
	"void",
	"PI",
	"TAU",
	"INF",
	"NAN",
	"true",
	"false",
	"null",
	"not",
	"and",
	"or",
	"in",
	"super",
]

var _plugin_config: SpacetimeDBPluginConfig
var _schema_path: String


func _init(p_schema_path: String) -> void:
	_schema_path = p_schema_path


## Builds a BSATN type string from the nested_type array (from schema parser).
## nested_type contains wrapper names in outside-in order, e.g., ["Option", "Array", "Option"]
## skip_outermost: true for struct fields/args (outer wrapper encoded in GDScript type),
##                 false for enum variants and return types (BSATN includes all wrappers)
static func _build_bsatn_type(nested_type: Array, base_meta_type: String, skip_outermost: bool = true) -> String:
	var bsatn: String = base_meta_type
	var start_idx: int = 1 if skip_outermost and not nested_type.is_empty() else 0
	# Apply wrappers from inside-out
	for i in range(nested_type.size() - 1, start_idx - 1, -1):
		match StringName(nested_type[i]):
			&"Array":
				bsatn = "vec_%s" % bsatn
			&"Option":
				bsatn = "opt_%s" % bsatn
	return bsatn


## Determines the GDScript field type from the nested_type array.
static func _gd_type_from_nested(nested_type: Array, base_gd_type: String) -> String:
	if nested_type.is_empty():
		return base_gd_type
	match StringName(nested_type[0]):
		&"Option":
			return OPTION_CLASS_NAME
		&"Array":
			if nested_type.size() >= 2 and StringName(nested_type[1]) == &"Option":
				return "Array[%s]" % OPTION_CLASS_NAME
			elif nested_type.size() >= 2 and StringName(nested_type[1]) == &"Array":
				return "Array" # Can't express Array[Array] in GDScript
			else:
				return "Array[%s]" % base_gd_type
	return base_gd_type


## Escapes a field/param name if it collides with a GDScript reserved word.
static func _safe_name(field_name: String) -> String:
	if field_name in GDSCRIPT_RESERVED_WORDS:
		return field_name + "_"
	return field_name


## Safely accesses schema.types by index, returning null if out of bounds.
static func _get_type_def(schema: SpacetimeParsedSchema, type_idx: int):
	if type_idx < 0 or type_idx >= schema.types.size():
		return null
	return schema.types[type_idx]


func generate_bindings() -> Array[String]:
	var generated_files: Array[String] = []

	for module_name: String in _plugin_config.module_configs:
		generated_files.append_array(_generate_module_bindings(module_name))

	var autoload_content := _generate_autoload_gdscript(_plugin_config.module_configs.keys())
	var autoload_output_file_path := "%s/%s" % [_schema_path, SpacetimePlugin.AUTOLOAD_FILE_NAME]
	var autoload_file := FileAccess.open(autoload_output_file_path, FileAccess.WRITE)
	if autoload_file:
		autoload_file.store_string(autoload_content)
		autoload_file.close()
		generated_files.append(autoload_output_file_path)

	SpacetimePlugin.print_log("Generated files:")
	for generated_file in generated_files:
		SpacetimePlugin.print_log(generated_file)

	return generated_files


## Scans all global classes and autoloads in the project for GDScript enums.
## Returns {enum_name: {path: "ClassName.EnumName", variants: ["A", "B", ...]}}
func _scan_project_enums() -> Dictionary:
	var result: Dictionary = { }
	# Scan global classes (scripts with class_name)
	var global_classes: Array[Dictionary] = ProjectSettings.get_global_class_list()
	for cls in global_classes:
		var cls_name: String = cls.get("class", "")
		var cls_path: String = cls.get("path", "")
		# Skip generated bindings and addons
		if cls_path.begins_with(SpacetimePlugin.BINDINGS_PATH):
			continue
		if cls_path.begins_with("res://addons/"):
			continue
		_collect_enums_from_script(cls_name, cls_path, result)
	# Scan autoloads (may not have class_name, may use uid:// paths)
	for prop in ProjectSettings.get_property_list():
		var prop_name: String = prop.get("name", "")
		if not prop_name.begins_with("autoload/"):
			continue
		var autoload_name: String = prop_name.trim_prefix("autoload/")
		var autoload_path: String = ProjectSettings.get_setting(prop_name, "")
		if autoload_path.begins_with("*"):
			autoload_path = autoload_path.substr(1)
		# Resolve uid:// to res:// for filtering
		var resolved_path: String = autoload_path
		if autoload_path.begins_with("uid://"):
			resolved_path = ResourceUID.get_id_path(ResourceUID.text_to_id(autoload_path))
		if resolved_path.begins_with(SpacetimePlugin.BINDINGS_PATH):
			continue
		if resolved_path.begins_with("res://addons/"):
			continue
		_collect_enums_from_script(autoload_name, autoload_path, result)
	return result


func _collect_enums_from_script(cls_name: String, cls_path: String, result: Dictionary) -> void:
	var script = load(cls_path)
	if not script or not script is GDScript:
		return
	var constants: Dictionary = script.get_script_constant_map()
	for const_name: String in constants:
		var value = constants[const_name]
		# GDScript enums appear as Dictionary with int values in constant map
		if value is Dictionary and not value.is_empty():
			var is_enum := true
			var variants: Array[String] = []
			for k in value:
				if not value[k] is int:
					is_enum = false
					break
				variants.append(str(k))
			if is_enum:
				result[const_name] = {
					"path": "%s.%s" % [cls_name, const_name],
					"variants": variants,
				}


func _generate_module_bindings(module_name: String):
	var json = JSON.parse_string(_plugin_config.module_configs[module_name].unparsed_module_schema)
	var project_enums := _scan_project_enums()
	var schema := SpacetimeSchemaParser.parse_schema(json, module_name, project_enums)
	_plugin_config.module_configs[module_name].unparsed_module_schema = ""
	if schema.is_empty():
		SpacetimePlugin.print_err("Schema parsing failed for module: %s. Aborting codegen for this module." % module_name)
		return []

	for folder in REQUIRED_FOLDERS_IN_CODEGEN_FOLDER:
		var folder_path := "%s/%s" % [_schema_path, folder]
		if not DirAccess.dir_exists_absolute(folder_path):
			DirAccess.make_dir_recursive_absolute(folder_path)

	var debug_dir_path := "%s/%s" % [SpacetimePlugin.BINDINGS_PATH, "codegen_debug"]
	if not DirAccess.dir_exists_absolute(debug_dir_path):
		DirAccess.make_dir_recursive_absolute(debug_dir_path)

	var file := FileAccess.open("%s/readme.txt" % [debug_dir_path], FileAccess.WRITE)
	if file:
		file.store_string("You can delete this directory and files. It's only used for codegen debugging.")
	file = FileAccess.open("%s/schema_%s.json" % [debug_dir_path, module_name], FileAccess.WRITE)
	if file:
		file.store_string(JSON.stringify(schema.to_dictionary(), "\t", false))
	file = FileAccess.open("%s/unparsed_schema_%s.json" % [debug_dir_path, module_name], FileAccess.WRITE)
	if file:
		file.store_string(JSON.stringify(json, "\t", false))
	var generated_files := _generate_gdscript_from_schema(module_name, schema)
	return generated_files


func _generate_gdscript_from_schema(module_name: String, schema: SpacetimeParsedSchema) -> Array[String]:
	var generated_files: Array[String] = []

	for type_def in schema.types:
		if type_def.has("gd_native"):
			continue

		var content: String
		if type_def.has("struct"):
			var generated_table_names: Array[String]
			if type_def.has("table_names"):
				var table_names_arr: Array = type_def.get("table_names", [])
				for i in table_names_arr.size():
					var tbl_name: String = table_names_arr[i]
					if _plugin_config.module_configs[module_name].hide_private_tables and not type_def.get("is_public", [])[i]:
						SpacetimePlugin.print_log("Skipping private table %s" % tbl_name)
						continue
					generated_table_names.append(tbl_name)

			content = _generate_struct_gdscript(schema, type_def, generated_table_names)
		elif type_def.has("enum"):
			if not type_def.get("is_sum_type"):
				continue
			content = _generate_enum_gdscript(schema, type_def)

		var output_file_name := "%s_%s.gd" % \
		[schema.module.to_snake_case(), type_def.get("name", "").to_snake_case()]
		var folder_path := "%s/types" % _schema_path
		var output_file_path := "%s/%s" % [folder_path, output_file_name]
		if not DirAccess.dir_exists_absolute(folder_path):
			DirAccess.make_dir_recursive_absolute(folder_path)

		var file := FileAccess.open(output_file_path, FileAccess.WRITE)
		if file:
			file.store_string(content)
			file.close()
			generated_files.append(output_file_path)

	for table_def in schema.tables:
		var table_name = table_def.get("name", null)
		if table_name == null:
			continue
		if _plugin_config.module_configs[module_name].hide_private_tables and not table_def.get("is_public", true):
			SpacetimePlugin.print_log("Skipping private table: %s" % table_name)
			continue

		var unique_indexes = table_def.get("unique_indexes", [])
		for unique_index in unique_indexes:
			var content := _generate_table_unique_index_gdscript(schema, unique_index, table_def)

			var output_file_name := "%s_%s_%s_unique_index.gd" % \
			[schema.module.to_snake_case(), table_name.to_snake_case(), unique_index.get("name", "").to_snake_case()]
			var folder_path := "%s/tables" % _schema_path
			var output_file_path := "%s/%s" % [folder_path, output_file_name]
			if not DirAccess.dir_exists_absolute(folder_path):
				DirAccess.make_dir_recursive_absolute(folder_path)

			var file := FileAccess.open(output_file_path, FileAccess.WRITE)
			if file:
				file.store_string(content)
				file.close()
				generated_files.append(output_file_path)

		var content := _generate_table_gdscript(schema, table_def)

		var output_file_name := "%s_%s_table.gd" % \
		[schema.module.to_snake_case(), table_name.to_snake_case()]
		var folder_path := "%s/tables" % _schema_path
		var output_file_path := "%s/%s" % [folder_path, output_file_name]
		if not DirAccess.dir_exists_absolute(folder_path):
			DirAccess.make_dir_recursive_absolute(folder_path)

		var file := FileAccess.open(output_file_path, FileAccess.WRITE)
		if file:
			file.store_string(content)
			file.close()
			generated_files.append(output_file_path)

	var module_content := _generate_module_client_gdscript(module_name, schema)
	var output_file_name_module := "module_%s_client.gd" % schema.module.to_snake_case()
	var output_file_path_module := "%s/%s" % [_schema_path, output_file_name_module]
	var file_module := FileAccess.open(output_file_path_module, FileAccess.WRITE)
	if file_module:
		file_module.store_string(module_content)
		file_module.close()
		generated_files.append(output_file_path_module)

	var db_content := _generate_db_gdscript(module_name, schema)
	var db_output_file_name := "module_%s_db.gd" % schema.module.to_snake_case()
	var db_output_file_path := "%s/%s" % [_schema_path, db_output_file_name]
	var db_file := FileAccess.open(db_output_file_path, FileAccess.WRITE)
	if db_file:
		db_file.store_string(db_content)
		db_file.close()
		generated_files.append(db_output_file_path)

	var reducers_content := _generate_reducers_gdscript(module_name, schema)
	var output_file_name_reducers := "module_%s_reducers.gd" % schema.module.to_snake_case()
	var output_file_path_reducers := "%s/%s" % [_schema_path, output_file_name_reducers]
	var file_reducers := FileAccess.open(output_file_path_reducers, FileAccess.WRITE)
	if file_reducers:
		file_reducers.store_string(reducers_content)
		file_reducers.close()
		generated_files.append(output_file_path_reducers)

	var procedures_content := _generate_procedures_gdscript(module_name, schema)
	var output_file_name_procedures := "module_%s_procedures.gd" % schema.module.to_snake_case()
	var output_file_path_procedures := "%s/%s" % [_schema_path, output_file_name_procedures]
	var file_procedures := FileAccess.open(output_file_path_procedures, FileAccess.WRITE)
	if file_procedures:
		file_procedures.store_string(procedures_content)
		file_procedures.close()
		generated_files.append(output_file_path_procedures)

	var types_content := _generate_types_gdscript(module_name, schema)
	var output_file_name_types := "module_%s_types.gd" % schema.module.to_snake_case()
	var output_file_path_types := "%s/%s" % [_schema_path, output_file_name_types]
	var file_types := FileAccess.open(output_file_path_types, FileAccess.WRITE)
	if file_types:
		file_types.store_string(types_content)
		file_types.close()
		generated_files.append(output_file_path_types)

	return generated_files


func _generate_table_unique_index_gdscript(schema: SpacetimeParsedSchema, unique_index_def: Dictionary, table_def: Dictionary) -> String:
	var table_name: String = table_def.get("name", "")
	var field_name: String = unique_index_def.get("name", "")
	var original_field_type: String = unique_index_def.get("type", "Variant")
	var field_type: String = schema.type_map.get(original_field_type, "Variant")
	var type_def: Dictionary = _get_type_def(schema, table_def.get("type_idx", -1)) if table_def.has("type_idx") else { }
	var original_type_name: String = type_def.get("name", "Variant")
	var type_name: String = schema.type_map.get(original_type_name, "Variant")

	var _class_name := "%s%s%sUniqueIndex" % \
	[schema.module.to_pascal_case(), table_name.to_pascal_case(), field_name.to_pascal_case()]
	var content: String = AUTOGENERATED_COMMENT +
	"class_name %s extends _ModuleTableUniqueIndex\n\n" % _class_name +
	"var _cache: Dictionary[%s, %s] = {}\n\n" % [field_type, type_name] +
	"func _init(p_local_db: LocalDatabase) -> void:\n" +
	"\t_table_name = &\"%s\"\n" % table_name +
	"\t_field_name = &\"%s\"\n" % field_name +
	"\t_connect_cache_to_db(_cache, p_local_db)\n\n" +
	"func find(col_val: %s) -> %s:\n" % [field_type, type_name] +
	"\treturn _cache.get(col_val, null)\n"

	return content


func _generate_table_gdscript(schema: SpacetimeParsedSchema, table_def: Dictionary) -> String:
	var table_name: String = table_def.get("name", "")
	var type_def: Dictionary = _get_type_def(schema, table_def.get("type_idx", -1)) if table_def.has("type_idx") else { }
	var original_type_name: String = type_def.get("name", "Variant")
	var type_name: String = schema.type_map.get(original_type_name, "Variant")
	var unique_index_fields: Dictionary[String, String] = { }
	for unique_index_def in table_def.get("unique_indexes", []):
		var field_name: String = unique_index_def.get("name", "")
		var unique_index_class_name := "%s%s%sUniqueIndex" % \
		[schema.module.to_pascal_case(), table_name.to_pascal_case(), field_name.to_pascal_case()]
		unique_index_fields[field_name] = unique_index_class_name

	var _class_name := "%s%sTable" % [schema.module.to_pascal_case(), table_name.to_pascal_case()]
	var content: String = AUTOGENERATED_COMMENT +
	"class_name %s extends _ModuleTable\n\n" % _class_name
	for field_name in unique_index_fields:
		var unique_index_class_name := unique_index_fields[field_name]
		content += "var %s: %s\n" % [field_name, unique_index_class_name]

	content += "\nfunc _init(p_local_db: LocalDatabase) -> void:\n" +
	"\tsuper(p_local_db)\n" +
	"\t_table_name = &\"%s\"\n" % table_name

	for field_name in unique_index_fields:
		var unique_index_class_name := unique_index_fields[field_name]
		content += "\t%s = %s.new(p_local_db)\n" % [field_name, unique_index_class_name]

	content += "\nfunc iter() -> Array[%s]:\n" % type_name +
	"\tvar rows: Array[_ModuleTableType] = super()\n" +
	"\tvar typed_array: Array[%s] = []\n" % type_name +
	"\ttyped_array.assign(rows)\n" +
	"\treturn typed_array\n"

	content += "\nfunc find_where(predicate: Callable) -> Array[%s]:\n" % type_name +
	"\tvar rows: Array = super(predicate)\n" +
	"\tvar typed_array: Array[%s] = []\n" % type_name +
	"\ttyped_array.assign(rows)\n" +
	"\treturn typed_array\n"

	content += "\nfunc first_where(predicate: Callable) -> %s:\n" % type_name +
	"\treturn super(predicate) as %s\n" % type_name

	content += "\nfunc find_by(field: StringName, value: Variant) -> Array[%s]:\n" % type_name +
	"\tvar rows: Array = super(field, value)\n" +
	"\tvar typed_array: Array[%s] = []\n" % type_name +
	"\ttyped_array.assign(rows)\n" +
	"\treturn typed_array\n"

	content += "\nfunc first_by(field: StringName, value: Variant) -> %s:\n" % type_name +
	"\treturn super(field, value) as %s\n" % type_name

	return content


func _generate_struct_gdscript(schema: SpacetimeParsedSchema, type_def: Dictionary, table_names: Array[String]) -> String:
	var struct_name: String = type_def.get("name", "")
	var fields: Array = type_def.get("struct", [])
	var bsatn_type_entries: Array = [] # Collected as ["\"FieldName\": &\"type\"", ...]
	var primary_key_name: String = ""
	var table_name: String = type_def.get("table_name", "")
	var _class_name: String = schema.module.to_pascal_case() + struct_name.to_pascal_case()
	var _extends_class = "Resource"
	if table_name:
		_extends_class = "_ModuleTableType"
		if table_names.size() != 0:
			primary_key_name = type_def.get("primary_key_name", "")

	var header: String = AUTOGENERATED_COMMENT +
	"@tool\n" +
	"class_name %s extends %s\n\n" % [_class_name, _extends_class] +
	"const module_name : String = \"%s\"\n" % schema.module +
	"const table_names: Array[StringName] = [%s]\n" % \
	[", ".join(table_names.map(func(x): return "&'%s'" % x))]

	var class_fields: Array = []
	var field_lines: String = ""
	var create_func_documentation_comment: String = ""
	# format for create_func_documentation_comment
	var format_cfdc: Callable = func(index, field_name, nested_type) -> String:
		return "## %d. %s: %s[br]\n" % [index, field_name, " of ".join(nested_type)]

	for i in fields.size():
		var field: Dictionary = fields[i]
		var field_name: String = _safe_name(field.get("name", ""))
		var original_type_name: String = field.get("type", "Variant")
		var field_type = _get_type_def(schema, field.type_idx) if field.has("type_idx") else null
		var gd_field_type: String = "Variant"
		var bsatn_meta_type_string: String = ""
		var documentation_comment: String = ""
		var nested_type: Array = field.get("nested_type", []).duplicate()
		nested_type.append(schema.type_map.get(original_type_name, "Variant"))
		var add_meta_for_field = false

		var parser_nested_type: Array = field.get("nested_type", [])
		if not parser_nested_type.is_empty():
			# Has nesting — use nested_type to determine GDScript type and BSATN
			gd_field_type = _gd_type_from_nested(parser_nested_type, schema.type_map.get(original_type_name, "Variant"))
			var base_meta: String = schema.meta_type_map.get(original_type_name, original_type_name)
			# Add gd_arraylike component types if inner type is a native arraylike (Vector2, etc.)
			if field_type and field_type.has("gd_arraylike"):
				var inner_meta_bsatn_types: Array[String] = []
				for el in field_type.struct:
					inner_meta_bsatn_types.append(schema.meta_type_map.get(el.type, "f32"))
				base_meta += "[%s]" % ",".join(inner_meta_bsatn_types)
			bsatn_meta_type_string = _build_bsatn_type(parser_nested_type, base_meta, true)
			if nested_type.size() > 1:
				documentation_comment = "## %s" % [" of ".join(nested_type)]
			create_func_documentation_comment += format_cfdc.call(i, field_name, nested_type)
			add_meta_for_field = true
		elif field_type and field_type.has("gd_arraylike"):
			create_func_documentation_comment += format_cfdc.call(i, field_name, nested_type)
			gd_field_type = schema.type_map.get(original_type_name, "Variant")
			var outer_bsatn_type = schema.meta_type_map.get(original_type_name, original_type_name)
			var inner_meta_bsatn_types: Array[String] = []
			for el in field_type.struct:
				var inner_bsatn_type = schema.meta_type_map.get(el.type, "f32")
				inner_meta_bsatn_types.append(inner_bsatn_type)
			bsatn_meta_type_string = "%s[%s]" % [outer_bsatn_type, ",".join(inner_meta_bsatn_types)]
			add_meta_for_field = true
		else:
			gd_field_type = schema.type_map.get(original_type_name, "Variant")
			bsatn_meta_type_string = schema.meta_type_map.get(original_type_name, original_type_name)
			create_func_documentation_comment += format_cfdc.call(i, field_name, nested_type)
			add_meta_for_field = schema.meta_type_map.has(original_type_name) \
			or not SpacetimeSchemaParser._is_gd_native(original_type_name)
		if field_name == "scheduled_at":
			bsatn_meta_type_string = "scheduled_at"
		if add_meta_for_field and not bsatn_meta_type_string.is_empty():
			bsatn_type_entries.append("&\"%s\": &\"%s\"" % [field_name, bsatn_meta_type_string])

		var field_line = "@export var %s: %s %s\n" % [field_name, gd_field_type, documentation_comment]
		field_lines += field_line.rstrip(" \n") + "\n"
		class_fields.append([field_name, gd_field_type])

	# Assemble: header, then constants, then fields, then create func
	var content: String = header
	if not primary_key_name.is_empty():
		content += "const PRIMARY_KEY: StringName = &\"%s\"\n" % primary_key_name
	if bsatn_type_entries.size() > 0:
		content += "const BSATN_TYPES: Dictionary[StringName, StringName] = { %s }\n" % ", ".join(bsatn_type_entries)
	content += "\n" + field_lines + "\n" + create_func_documentation_comment
	content += "static func create(%s) -> %s:\n" % \
	[", ".join(class_fields.map(func(x): return "p_%s: %s" % [x[0], x[1]])), _class_name] +
	"\tvar result: %s = %s.new()\n" % [_class_name, _class_name]
	for field_data in class_fields:
		var f_name: String = field_data[0]
		content += "\tresult.%s = p_%s\n" % [f_name, f_name]
	content += "\treturn result\n"
	return content


func _generate_enum_gdscript(schema: SpacetimeParsedSchema, type_def: Dictionary) -> String:
	var enum_name: String = type_def.get("name", "")
	var variants: Array = type_def.get("enum", [""])
	var variant_names: String = "\n".join(
		variants.map(
			func(x):
				return "\t%s," % [x.get("name", "")]
		),
	)

	var _class_name: String = schema.module.to_pascal_case() + enum_name.to_pascal_case()
	var enum_options_entries: String = ", ".join(
		variants.map(
			func(x):
				var type = x.get("type", "")
				var rust_type = schema.meta_type_map.get(type, type)
				var variant_nested: Array = x.get("nested_type", [])
				if not variant_nested.is_empty():
					rust_type = SpacetimeCodegen._build_bsatn_type(variant_nested, rust_type, false)
				return "&'%s'" % rust_type if not rust_type.is_empty() else "&''"
		),
	)

	var content: String = AUTOGENERATED_COMMENT +
	"class_name %s extends RustEnum\n\n" % _class_name +
	"enum Options {\n%s\n}\n\n" % variant_names +
	"const ENUM_OPTIONS: Array[StringName] = [%s]\n\n" % enum_options_entries +
	"static func parse_enum_name(i: int) -> String:\n" +
	"\tmatch i:\n"
	for i in range(variants.size()):
		content += "\t\t%d: return &'%s'\n" % [i, variants[i].get("name", "")]
	content += "\t\t_:\n" +
	"\t\t\tprinterr(\"Enum does not have value for %d. This is out of bounds.\" % i)\n" +
	"\t\t\treturn &'Unknown'\n\n"
	var get_funcs: Array[String] = []
	var create_funcs: Array[String] = []
	for v_schema in variants:
		var variant_name: String = v_schema.get("name", "")
		var variant_gd_type: String = schema.type_map.get(v_schema.get("type", ""), "Variant")
		var nested_type: Array = v_schema.get("nested_type", []).duplicate()
		nested_type.append(variant_gd_type)
		var variant_nested: Array = v_schema.get("nested_type", [])
		if not variant_nested.is_empty():
			variant_gd_type = _gd_type_from_nested(variant_nested, variant_gd_type)

		if v_schema.has("type"):
			var has_option_in_nesting: bool = variant_nested.has(&"Option")
			if has_option_in_nesting:
				get_funcs.append(
					"## Returns: %s\n" % \
					[" of ".join(nested_type)],
				)
				create_funcs.append(
					"## 0. data: %s\n" % \
					[" of ".join(nested_type)],
				)
			get_funcs.append(
				"func get_%s() -> %s:\n" % [variant_name.to_snake_case(), variant_gd_type] +
				"\treturn data\n\n",
			)
			create_funcs.append(
				"static func create_%s(_data: %s) -> %s:\n" % [variant_name.to_snake_case(), variant_gd_type, _class_name] +
				"\treturn create(Options.%s, _data)\n\n" % [variant_name],
			)
		else:
			create_funcs.append(
				"static func create_%s() -> %s:\n" % [variant_name.to_snake_case(), _class_name] +
				"\treturn create(Options.%s)\n\n" % [variant_name],
			)

	content += "".join(get_funcs)
	content += "static func create(p_type: int, p_data: Variant = null) -> %s:\n" % _class_name +
	"\tvar result : %s = %s.new()\n" % [_class_name, _class_name] +
	"\tresult.value = p_type\n" +
	"\tresult.data = p_data\n" +
	"\treturn result\n\n"
	content += "".join(create_funcs)

	return content


func _generate_module_client_gdscript(module_name: String, schema: SpacetimeParsedSchema) -> String:
	var content := AUTOGENERATED_COMMENT +
	"@tool\n" +
	"class_name %sModuleClient extends SpacetimeDBClient\n\n" % schema.module.to_pascal_case()

	content += "var reducers: %sModuleReducers\n" % schema.module.to_pascal_case() +
	"var procedures: %sModuleProcedures\n" % schema.module.to_pascal_case() +
	"var db: %sModuleDb\n\n" % schema.module.to_pascal_case() +
	"func _init() -> void:\n" +
	"\tmodule_name = \"%s\"\n" % schema.module +
	"\tname = \"%sModule\"\n" % schema.module.to_pascal_case() +
	"\treducers = preload('%s/module_%s_reducers.gd').new(self)\n" % [_schema_path, schema.module.to_snake_case()] +
	"\tprocedures = preload('%s/module_%s_procedures.gd').new(self)\n" % [_schema_path, schema.module.to_snake_case()] +
	"\nfunc _init_db(p_local_db: LocalDatabase) -> void:\n" +
	"\tdb = preload('%s/module_%s_db.gd').new(p_local_db)\n" % [_schema_path, schema.module.to_snake_case()]

	return content


func _generate_db_gdscript(module_name: String, schema: SpacetimeParsedSchema) -> String:
	var tables: Dictionary[String, String] = { }
	var table_names: Array[String] = []
	for table_def in schema.tables:
		var table_name = table_def.get("name", null)
		if table_name == null:
			continue
		if _plugin_config.module_configs[module_name].hide_private_tables and not table_def.get("is_public", true):
			continue
		tables[table_name] = "%s%sTable" % [schema.module.to_pascal_case(), table_name.to_pascal_case()]
		table_names.append("&\"%s\"" % table_name)

	var content := AUTOGENERATED_COMMENT +
	"class_name %sModuleDb extends RefCounted\n\n" % schema.module.to_pascal_case() +
	"const table_names : Array[StringName] = [%s]\n\n" % ", ".join(table_names)
	for table_name in tables:
		var table_type := tables[table_name]
		content += "var %s: %s\n" % [table_name.to_snake_case(), table_type]

	content += "\nfunc _init(p_local_db: LocalDatabase) -> void:\n"
	for table_name in tables:
		content += "\t%s = preload('%s/tables/%s_%s_table.gd').new(p_local_db)\n" % \
		[table_name.to_snake_case(), _schema_path, schema.module.to_snake_case(), table_name.to_snake_case()]

	return content


func _generate_types_gdscript(module_name: String, schema: SpacetimeParsedSchema) -> String:
	var class_name_line := "class_name %sTypes\n\n" % module_name.to_pascal_case()
	var content := AUTOGENERATED_COMMENT + class_name_line
	for _type_def in schema.types:
		if _type_def.has("gd_native"):
			continue
		var type_name: String = _type_def.get("name", "")
		if _type_def.has("table_name"):
			if not _type_def.has("primary_key_name"):
				continue
			if _plugin_config.module_configs[module_name].hide_private_tables and not _type_def.get("is_public", []).has(true):
				continue

		if _type_def.has("is_sum_type") and not _type_def.get("is_sum_type"):
			if _type_def.has("project_enum"):
				continue # Skip — using project's existing enum
			content += "enum %s {\n" % type_name.to_pascal_case()
			var variants_str := ""
			for variant in _type_def.get("enum", []):
				var variant_name: String = variant.get("name", "")
				variants_str += "\t%s,\n" % variant_name.to_pascal_case()
			if not variants_str.is_empty():
				variants_str = variants_str.left(-2)
			content += variants_str
			content += "\n}\n"
		else:
			content += "const %s = preload('%s/types/%s_%s.gd')\n" % \
			[
				type_name.to_pascal_case(),
				_schema_path,
				schema.module.to_snake_case(),
				type_name.to_snake_case(),
			]
	return content


func _generate_reducers_gdscript(module_name: String, schema: SpacetimeParsedSchema) -> String:
	var content := AUTOGENERATED_COMMENT +
	"class_name %sModuleReducers extends RefCounted\n\n" % schema.module.to_pascal_case() +
	"var _client: SpacetimeDBClient\n\n" +
	"func _init(p_client: SpacetimeDBClient) -> void:\n" +
	"\t_client = p_client\n"

	for reducer in schema.reducers:
		if reducer.get("is_scheduled", false) and _plugin_config.module_configs[module_name].hide_scheduled_reducers:
			continue

		var params_str_parts: Array[String] = []
		var description_comment: Array = []
		var reducer_params = reducer.get("params", [])
		for i in reducer_params.size():
			var param = reducer_params[i]
			var param_name: String = _safe_name(param.get("name", ""))
			var gd_param_type: String
			var original_inner_type_name: String = param.get("type", "Variant")
			var nested_type: Array = param.get("nested_type", []).duplicate()
			nested_type.append(schema.type_map.get(original_inner_type_name, "Variant"))
			description_comment.append("## %d. %s: %s [br]" % [i, param_name, " of ".join(nested_type)])
			var param_nested: Array = param.get("nested_type", [])
			if not param_nested.is_empty():
				gd_param_type = _gd_type_from_nested(param_nested, schema.type_map.get(original_inner_type_name, "Variant"))
			else:
				gd_param_type = schema.type_map.get(original_inner_type_name, "Variant")
			params_str_parts.append("%s: %s" % [param_name, gd_param_type])

		var params_str: String
		if params_str_parts.is_empty():
			params_str = ""
		else:
			params_str = ", ".join(params_str_parts)

		var param_names_list = reducer.get("params", []).map(func(x): return _safe_name(x.get("name", "")))
		var param_names_str = ""
		if not param_names_list.is_empty():
			param_names_str = ", ".join(param_names_list)

		var param_bsatn_types_list = (reducer.get("params", []) as Array).map(
			func(x):
				var original_inner_type_name_bsatn: String = x.get("type", "Variant")
				var param_type = _get_type_def(schema, x.type_idx) if x.has("type_idx") else null
				var bsatn_param_type: String
				var p_nested: Array = x.get("nested_type", [])

				if not p_nested.is_empty():
					var base_meta: String = schema.meta_type_map.get(original_inner_type_name_bsatn, original_inner_type_name_bsatn)
					if param_type and param_type.has("gd_arraylike"):
						var inner_meta_bsatn_types: Array[String] = []
						for el in param_type.struct:
							inner_meta_bsatn_types.append(schema.meta_type_map.get(el.type, "f32"))
						base_meta += "[%s]" % ",".join(inner_meta_bsatn_types)
					bsatn_param_type = SpacetimeCodegen._build_bsatn_type(p_nested, base_meta, true)
				elif param_type and param_type.has("gd_arraylike"):
					var outer_bsatn_type = schema.meta_type_map.get(original_inner_type_name_bsatn, original_inner_type_name_bsatn)
					var inner_meta_bsatn_types: Array[String] = []
					for el in param_type.struct:
						var inner_bsatn_type = schema.meta_type_map.get(el.type, "f32")
						inner_meta_bsatn_types.append(inner_bsatn_type)
					bsatn_param_type = "%s[%s]" % [outer_bsatn_type, ",".join(inner_meta_bsatn_types)]
				else:
					bsatn_param_type = schema.meta_type_map.get(original_inner_type_name_bsatn, original_inner_type_name_bsatn)

	if bsatn_param_type.is_empty():
		return "''"
	return "&'%s'" % bsatn_param_type
		)
		var param_bsatn_types_str := ""
		if not param_bsatn_types_list.is_empty():
			param_bsatn_types_str = ", ".join(param_bsatn_types_list)

		content += "\n".join(description_comment) + "\n"
		var reducer_name: String = reducer.get("name", "")
		content += "func %s(%s) -> SpacetimeDBReducerCall:\n" % [reducer_name, params_str] +
		"\treturn _client.call_reducer('%s', [%s], [%s])\n\n" % \
		[reducer_name, param_names_str, param_bsatn_types_str]

	return content

func _generate_procedures_gdscript(module_name: String, schema: SpacetimeParsedSchema) -> String:


	var content := AUTOGENERATED_COMMENT +
	"class_name %sModuleProcedures extends RefCounted\n\n" % schema.module.to_pascal_case() +
	"var _client: SpacetimeDBClient\n\n" +
	"func _init(p_client: SpacetimeDBClient) -> void:\n" +
	"\t_client = p_client\n"

	for proc in schema.procedures:
		var params_str_parts: Array[String] = []
		var description_comment: Array = []
		var proc_params = proc.get("params", [])
		for i in proc_params.size():
			var param = proc_params[i]
			var param_name: String = _safe_name(param.get("name", ""))
			var gd_param_type: String
			var original_inner_type_name: String = param.get("type", "Variant")
			var nested_type: Array = param.get("nested_type", []).duplicate()
			nested_type.append(schema.type_map.get(original_inner_type_name, "Variant"))
			description_comment.append("## %d. %s: %s [br]" % [i, param_name, " of ".join(nested_type)])
			var param_nested: Array = param.get("nested_type", [])
			if not param_nested.is_empty():
				gd_param_type = _gd_type_from_nested(param_nested, schema.type_map.get(original_inner_type_name, "Variant"))
			else:
				gd_param_type = schema.type_map.get(original_inner_type_name, "Variant")
			params_str_parts.append("%s: %s" % [param_name, gd_param_type])

		# Build return type description
		var ret_data: Dictionary = proc.get("return_data", { })
		var ret_type_name: String = proc.get("return_type", "Variant")
		var ret_gd_type: String = schema.type_map.get(ret_type_name, ret_type_name)
		var ret_nested: Array = ret_data.get("nested_type", [])
		var ret_desc: String = ret_gd_type
		if not ret_nested.is_empty():
			var ret_nested_display: Array = ret_nested.duplicate()
			ret_nested_display.append(ret_gd_type)
			ret_desc = " of ".join(ret_nested_display)
		description_comment.insert(0, "## Returns: %s [br]" % ret_desc)

		var params_str: String
		if params_str_parts.is_empty():
			params_str = ""
		else:
			params_str = ", ".join(params_str_parts)

		var param_names_list = proc.get("params", []).map(func(x): return _safe_name(x.get("name", "")))
		var param_names_str = ""
		if not param_names_list.is_empty():
			param_names_str = ", ".join(param_names_list)

		# Build BSATN types for params (same logic as reducers)
		var param_bsatn_types_list = (proc.get("params", []) as Array).map(
			func(x):
				var original_inner_type_name_bsatn: String = x.get("type", "Variant")
				var param_type = _get_type_def(schema, x.type_idx) if x.has("type_idx") else null
				var bsatn_param_type: String
				var p_nested: Array = x.get("nested_type", [])

				if not p_nested.is_empty():
					var base_meta: String = schema.meta_type_map.get(original_inner_type_name_bsatn, original_inner_type_name_bsatn)
					if param_type and param_type.has("gd_arraylike"):
						var inner_meta_bsatn_types: Array[String] = []
						for el in param_type.struct:
							inner_meta_bsatn_types.append(schema.meta_type_map.get(el.type, "f32"))
						base_meta += "[%s]" % ",".join(inner_meta_bsatn_types)
					bsatn_param_type = SpacetimeCodegen._build_bsatn_type(p_nested, base_meta, true)
				elif param_type and param_type.has("gd_arraylike"):
					var outer_bsatn_type = schema.meta_type_map.get(original_inner_type_name_bsatn, original_inner_type_name_bsatn)
					var inner_meta_bsatn_types: Array[String] = []
					for el in param_type.struct:
						var inner_bsatn_type = schema.meta_type_map.get(el.type, "f32")
						inner_meta_bsatn_types.append(inner_bsatn_type)
					bsatn_param_type = "%s[%s]" % [outer_bsatn_type, ",".join(inner_meta_bsatn_types)]
				else:
					bsatn_param_type = schema.meta_type_map.get(original_inner_type_name_bsatn, original_inner_type_name_bsatn)

				if bsatn_param_type.is_empty():
					return "''"
				return "&'%s'" % bsatn_param_type
		)
		var param_bsatn_types_str := ""
		if not param_bsatn_types_list.is_empty():
			param_bsatn_types_str = ", ".join(param_bsatn_types_list)

		# Build return BSATN type string for decode()
		var ret_bsatn_type: String = schema.meta_type_map.get(ret_type_name, ret_type_name)
		if not ret_nested.is_empty():
			ret_bsatn_type = _build_bsatn_type(ret_nested, ret_bsatn_type, false)

		content += "\n".join(description_comment) + "\n"
		var proc_name: String = proc.get("name", "")
		content += "func %s(%s) -> SpacetimeDBProcedureCall:\n" % [proc_name, params_str] +
		"\treturn _client.call_procedure('%s', [%s], [%s], &'%s')\n\n" % \
		[proc_name, param_names_str, param_bsatn_types_str, ret_bsatn_type]

	return content

func _generate_autoload_gdscript(modules: Array[String]) -> String:


	var content := AUTOGENERATED_COMMENT +
	"extends Node\n#SpacetimeDB Autoload\n\n"
	for module_name in modules:
		content += "var %s: %sModuleClient\n" % \
		[module_name.to_pascal_case(), module_name.to_pascal_case()]

	content += "\nfunc _init() -> void:\n"
	for module_name in modules:
		content += "\t%s = preload('%s/module_%s_client.gd').new()\n" % \
		[module_name.to_pascal_case(), _schema_path, module_name.to_snake_case()] +
		"\tadd_child(%s)\n" % [module_name.to_pascal_case()]

	return content
